apiVersion: v1
kind: ServiceAccount
metadata:
  name: twir-workloads
  namespace: twir
  labels:
    app.kubernetes.io/name: twir
imagePullSecrets:
  - name: registry-twir-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: twir
  labels:
    app.kubernetes.io/name: otel-collector
