/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,generate_dependencies,eslint_disable,server_none
// @generated from protobuf file "api.proto" (package "api", syntax proto3)
// tslint:disable
import { ParseHtmlOverlayResponse } from "./messages/overlays/overlays";
import { ParseHtmlOverlayRequest } from "./messages/overlays/overlays";
import { CreateRequest } from "./messages/overlays/overlays";
import { DeleteRequest } from "./messages/overlays/overlays";
import { UpdateRequest } from "./messages/overlays/overlays";
import { Overlay } from "./messages/overlays/overlays";
import { GetByIdRequest } from "./messages/overlays/overlays";
import { GetAllResponse } from "./messages/overlays/overlays";
import { PostCodeRequest as PostCodeRequest$ } from "./messages/integrations_streamlabs/integrations_streamlabs";
import { GetDataResponse as GetDataResponse$ } from "./messages/integrations_streamlabs/integrations_streamlabs";
import { GetAuthLink as GetAuthLink$ } from "./messages/integrations_streamlabs/integrations_streamlabs";
import { PostCodeRequest } from "./messages/integrations_faceit/integrations_faceit";
import { UpdateDataRequest } from "./messages/integrations_faceit/integrations_faceit";
import { GetDataResponse } from "./messages/integrations_faceit/integrations_faceit";
import { GetAuthLink } from "./messages/integrations_faceit/integrations_faceit";
import { Empty } from "./google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service api.Protected
 */
export const Protected = new ServiceType("api.Protected", [
    { name: "IntegrationsFaceitGetAuthLink", options: {}, I: Empty, O: GetAuthLink },
    { name: "IntegrationsFaceitGetData", options: {}, I: Empty, O: GetDataResponse },
    { name: "IntegrationsFaceitUpdate", options: {}, I: UpdateDataRequest, O: Empty },
    { name: "IntegrationsFaceitPostCode", options: {}, I: PostCodeRequest, O: Empty },
    { name: "IntegrationsFaceitLogout", options: {}, I: Empty, O: Empty },
    { name: "IntegrationsStreamlabsGetAuthLink", options: {}, I: Empty, O: GetAuthLink$ },
    { name: "IntegrationsStreamlabsGetData", options: {}, I: Empty, O: GetDataResponse$ },
    { name: "IntegrationsStreamlabsPostCode", options: {}, I: PostCodeRequest$, O: Empty },
    { name: "IntegrationsStreamlabsLogout", options: {}, I: Empty, O: Empty },
    { name: "OverlaysGetAll", options: {}, I: Empty, O: GetAllResponse },
    { name: "OverlaysGetOne", options: {}, I: GetByIdRequest, O: Overlay },
    { name: "OverlaysUpdate", options: {}, I: UpdateRequest, O: Overlay },
    { name: "OverlaysDelete", options: {}, I: DeleteRequest, O: Empty },
    { name: "OverlaysCreate", options: {}, I: CreateRequest, O: Overlay },
    { name: "OverlaysParseHtml", options: {}, I: ParseHtmlOverlayRequest, O: ParseHtmlOverlayResponse }
]);
