functions:
  argument:
    - name: buckets
      type: Array(Float64)
    - name: counts
      type: Array(Float64)
    - name: quantile
      type: Array(Float64)
  command: ./histogramQuantile
  format: CSV
  name: histogramQuantile
  return_type: Float64
  type: executable
