keeper_server:
  coordination_settings:
    force_sync: false
    operation_timeout_ms: 10000
    raft_logs_level: warning
    session_timeout_ms: 30000
    snapshot_distance: 100000
    snapshots_to_keep: 3
  four_letter_word_white_list: '*'
  log_storage_path: /var/lib/clickhouse/coordination/log
  raft_configuration:
    server:
      - hostname: signoz-clickhouse-keeper
        id: 0
        port: 9234
  server_id: 0
  snapshot_storage_path: /var/lib/clickhouse/coordination/snapshots
  tcp_port: 9181
listen_host: 0.0.0.0
logger:
  console: true
  level: information
