connectors:
  signozmeter:
    dimensions:
      - name: service.name
      - name: deployment.environment
      - name: host.name
    metrics_flush_interval: 1h

exporters:
  clickhouselogsexporter:
    dsn: tcp://signoz-clickhouse:9000/signoz_logs
    sending_queue:
      enabled: false
    timeout: 45s
    use_new_schema: true
  clickhousetraces:
    datasource: tcp://signoz-clickhouse:9000/signoz_traces
    low_cardinal_exception_grouping: ${env:LOW_CARDINAL_EXCEPTION_GROUPING}
    sending_queue:
      enabled: false
    timeout: 45s
    use_new_schema: true
  metadataexporter:
    cache:
      provider: in_memory
    dsn: tcp://signoz-clickhouse:9000/signoz_metadata
    enabled: true
    timeout: 45s
  signozclickhousemeter:
    dsn: tcp://signoz-clickhouse:9000/signoz_meter
    sending_queue:
      enabled: false
    timeout: 45s
  signozclickhousemetrics:
    dsn: tcp://signoz-clickhouse:9000/signoz_metrics
    sending_queue:
      enabled: false
    timeout: 45s

extensions:
  pprof:
    endpoint: 0.0.0.0:1777
  signoz_health_check:
    endpoint: 0.0.0.0:13133

processors:
  batch:
    send_batch_max_size: 55000
    send_batch_size: 50000
    timeout: 5s
  batch/meter:
    send_batch_max_size: 25000
    send_batch_size: 20000
    timeout: 5s
  signozspanmetrics/delta:
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    dimensions:
      - default: default
        name: service.namespace
      - default: default
        name: deployment.environment
      - name: signoz.collector.id
      - name: service.version
    dimensions_cache_size: 100000
    enable_exp_histogram: true
    latency_histogram_buckets:
      - 100us
      - 1ms
      - 2ms
      - 6ms
      - 10ms
      - 50ms
      - 100ms
      - 250ms
      - 500ms
      - 1000ms
      - 1400ms
      - 2000ms
      - 5s
      - 10s
      - 20s
      - 40s
      - 60s
    metrics_exporter: signozclickhousemetrics
    metrics_flush_interval: 60s

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

service:
  extensions:
    - signoz_health_check
    - pprof
  pipelines:
    logs:
      exporters:
        - clickhouselogsexporter
        - signozmeter
        - metadataexporter
      processors:
        - batch
      receivers:
        - otlp
    metrics:
      exporters:
        - signozclickhousemetrics
        - signozmeter
        - metadataexporter
      processors:
        - batch
      receivers:
        - otlp
    metrics/meter:
      exporters:
        - signozclickhousemeter
      processors:
        - batch/meter
      receivers:
        - signozmeter
    traces:
      exporters:
        - clickhousetraces
        - signozmeter
        - metadataexporter
      processors:
        - signozspanmetrics/delta
        - batch
      receivers:
        - otlp
  telemetry:
    logs:
      encoding: json
