// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: messages/integrations_lastfm/integrations_lastfm.proto

package integrations_lastfm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuthLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthLink) Reset() {
	*x = GetAuthLink{}
	mi := &file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthLink) ProtoMessage() {}

func (x *GetAuthLink) ProtoReflect() protoreflect.Message {
	mi := &file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthLink.ProtoReflect.Descriptor instead.
func (*GetAuthLink) Descriptor() ([]byte, []int) {
	return file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      *string                `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3,oneof" json:"user_name,omitempty"`
	Avatar        *string                `protobuf:"bytes,2,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescGZIP(), []int{1}
}

func (x *GetDataResponse) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *GetDataResponse) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type PostCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCodeRequest) Reset() {
	*x = PostCodeRequest{}
	mi := &file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCodeRequest) ProtoMessage() {}

func (x *PostCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCodeRequest.ProtoReflect.Descriptor instead.
func (*PostCodeRequest) Descriptor() ([]byte, []int) {
	return file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescGZIP(), []int{2}
}

func (x *PostCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_messages_integrations_lastfm_integrations_lastfm_proto protoreflect.FileDescriptor

const file_messages_integrations_lastfm_integrations_lastfm_proto_rawDesc = "" +
	"\n" +
	"6messages/integrations_lastfm/integrations_lastfm.proto\x12\x1cmessages.integrations_lastfm\"!\n" +
	"\vGetAuthLink\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\"i\n" +
	"\x0fGetDataResponse\x12 \n" +
	"\tuser_name\x18\x01 \x01(\tH\x00R\buserName\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x02 \x01(\tH\x01R\x06avatar\x88\x01\x01B\f\n" +
	"\n" +
	"_user_nameB\t\n" +
	"\a_avatar\"%\n" +
	"\x0fPostCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04codeB?Z=github.com/twirapp/twir/libs/api/messages/integrations_lastfmb\x06proto3"

var (
	file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescOnce sync.Once
	file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescData []byte
)

func file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescGZIP() []byte {
	file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescOnce.Do(func() {
		file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_integrations_lastfm_integrations_lastfm_proto_rawDesc), len(file_messages_integrations_lastfm_integrations_lastfm_proto_rawDesc)))
	})
	return file_messages_integrations_lastfm_integrations_lastfm_proto_rawDescData
}

var file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_messages_integrations_lastfm_integrations_lastfm_proto_goTypes = []any{
	(*GetAuthLink)(nil),     // 0: messages.integrations_lastfm.GetAuthLink
	(*GetDataResponse)(nil), // 1: messages.integrations_lastfm.GetDataResponse
	(*PostCodeRequest)(nil), // 2: messages.integrations_lastfm.PostCodeRequest
}
var file_messages_integrations_lastfm_integrations_lastfm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_integrations_lastfm_integrations_lastfm_proto_init() }
func file_messages_integrations_lastfm_integrations_lastfm_proto_init() {
	if File_messages_integrations_lastfm_integrations_lastfm_proto != nil {
		return
	}
	file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_integrations_lastfm_integrations_lastfm_proto_rawDesc), len(file_messages_integrations_lastfm_integrations_lastfm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_integrations_lastfm_integrations_lastfm_proto_goTypes,
		DependencyIndexes: file_messages_integrations_lastfm_integrations_lastfm_proto_depIdxs,
		MessageInfos:      file_messages_integrations_lastfm_integrations_lastfm_proto_msgTypes,
	}.Build()
	File_messages_integrations_lastfm_integrations_lastfm_proto = out.File
	file_messages_integrations_lastfm_integrations_lastfm_proto_goTypes = nil
	file_messages_integrations_lastfm_integrations_lastfm_proto_depIdxs = nil
}
