version: '2'
run:
  concurrency: 2
linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - gomodguard
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        all:
          deny:
            - pkg: io/ioutil
              desc: io/ioutil package has been deprecated
            - pkg: github.com/docker/docker/errdefs
              desc: use github.com/containerd/errdefs instead.
            - pkg: golang.org/x/exp/maps
              desc: use stdlib maps package
            - pkg: golang.org/x/exp/slices
              desc: use stdlib slices package
    gocritic:
      disabled-checks:
        - paramTypeCombine
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - opinionated
        - style
    gocyclo:
      min-complexity: 16
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
                - fmt
        versions:
          - github.com/distribution/distribution:
              reason: use distribution/reference
          - gotest.tools:
              version: < 3.0.0
              reason: deprecated, pre-modules version
    lll:
      line-length: 200
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/org/project) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
      custom-order: true # make the section order the same as the order of "sections".
