files:
  - source: /frontend/dashboard/src/locales/en.json
    translation: /frontend/dashboard/src/locales/%two_letters_code%.json
  - source: /apps/*/locales/en/**/*.yaml
    translation: /apps/*/locales/%two_letters_code%/**/*.yaml
    type: yaml
