preserve_hierarchy: true

#  "source": "/locale/en/**/*.po",
#  "translation": "/locale/%two_letters_code%/**/%original_file_name%"

files:
  - source: /frontend/dashboard/src/locales/en.json
    translation: /frontend/dashboard/src/locales/%two_letters_code%.json
  - source: /apps/*/locales/en/**/*.yaml
    translation: /apps/%original_path%/locales/%two_letters_code%/%original_file_name%
