FROM ubuntu:latest AS build_base

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update \ 
    && apt-get install -y openssl -y curl git protobuf-compiler wget

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install nodejs

RUN wget https://go.dev/dl/go1.19.1.linux-amd64.tar.gz && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.1.linux-amd64.tar.gz && rm go1.19.1.linux-amd64.tar.gz

ENV GOPATH=$HOME/go
ENV PATH=$PATH:$GOPATH/bin:/usr/local/go/bin

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28

RUN npm i -g pnpm@7 pm2

COPY . .
RUN pnpm install
RUN pnpm build:backend

CMD ["pnpm", "dev"]