/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,generate_dependencies,eslint_disable,server_none
// @generated from protobuf file "messages/integrations_nightbot/integrations_nightbot.proto" (package "messages.integrations_nightbot", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message messages.integrations_nightbot.GetAuthLink
 */
export interface GetAuthLink {
    /**
     * @generated from protobuf field: string link = 1;
     */
    link: string;
}
/**
 * @generated from protobuf message messages.integrations_nightbot.GetDataResponse
 */
export interface GetDataResponse {
    /**
     * @generated from protobuf field: optional string user_name = 1;
     */
    userName?: string;
    /**
     * @generated from protobuf field: optional string avatar = 2;
     */
    avatar?: string;
}
/**
 * @generated from protobuf message messages.integrations_nightbot.PostCodeRequest
 */
export interface PostCodeRequest {
    /**
     * @generated from protobuf field: string code = 1;
     */
    code: string;
}
/**
 * @generated from protobuf message messages.integrations_nightbot.ImportCommandsResponse
 */
export interface ImportCommandsResponse {
    /**
     * @generated from protobuf field: int32 imported_count = 1;
     */
    importedCount: number;
    /**
     * @generated from protobuf field: int32 failed_count = 2;
     */
    failedCount: number;
    /**
     * @generated from protobuf field: repeated string failed_commands_names = 3;
     */
    failedCommandsNames: string[];
}
/**
 * @generated from protobuf message messages.integrations_nightbot.ImportTimersResponse
 */
export interface ImportTimersResponse {
    /**
     * @generated from protobuf field: int32 imported_count = 1;
     */
    importedCount: number;
    /**
     * @generated from protobuf field: int32 failed_count = 2;
     */
    failedCount: number;
    /**
     * @generated from protobuf field: repeated string failed_timers_names = 3;
     */
    failedTimersNames: string[];
}
// @generated message type with reflection information, may provide speed optimized methods
class GetAuthLink$Type extends MessageType<GetAuthLink> {
    constructor() {
        super("messages.integrations_nightbot.GetAuthLink", [
            { no: 1, name: "link", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.integrations_nightbot.GetAuthLink
 */
export const GetAuthLink = new GetAuthLink$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDataResponse$Type extends MessageType<GetDataResponse> {
    constructor() {
        super("messages.integrations_nightbot.GetDataResponse", [
            { no: 1, name: "user_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "avatar", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.integrations_nightbot.GetDataResponse
 */
export const GetDataResponse = new GetDataResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostCodeRequest$Type extends MessageType<PostCodeRequest> {
    constructor() {
        super("messages.integrations_nightbot.PostCodeRequest", [
            { no: 1, name: "code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.integrations_nightbot.PostCodeRequest
 */
export const PostCodeRequest = new PostCodeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImportCommandsResponse$Type extends MessageType<ImportCommandsResponse> {
    constructor() {
        super("messages.integrations_nightbot.ImportCommandsResponse", [
            { no: 1, name: "imported_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "failed_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "failed_commands_names", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.integrations_nightbot.ImportCommandsResponse
 */
export const ImportCommandsResponse = new ImportCommandsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImportTimersResponse$Type extends MessageType<ImportTimersResponse> {
    constructor() {
        super("messages.integrations_nightbot.ImportTimersResponse", [
            { no: 1, name: "imported_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "failed_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "failed_timers_names", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.integrations_nightbot.ImportTimersResponse
 */
export const ImportTimersResponse = new ImportTimersResponse$Type();
