// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: messages/overlays_be_right_back/overlays_be_right_back.proto

package overlays_be_right_back

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Text            string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Late            *Settings_Late         `protobuf:"bytes,2,opt,name=late,proto3" json:"late,omitempty"`
	BackgroundColor string                 `protobuf:"bytes,3,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	FontSize        int32                  `protobuf:"varint,4,opt,name=font_size,json=fontSize,proto3" json:"font_size,omitempty"`
	FontColor       string                 `protobuf:"bytes,5,opt,name=font_color,json=fontColor,proto3" json:"font_color,omitempty"`
	FontFamily      string                 `protobuf:"bytes,6,opt,name=font_family,json=fontFamily,proto3" json:"font_family,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_messages_overlays_be_right_back_overlays_be_right_back_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_messages_overlays_be_right_back_overlays_be_right_back_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Settings) GetLate() *Settings_Late {
	if x != nil {
		return x.Late
	}
	return nil
}

func (x *Settings) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *Settings) GetFontSize() int32 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

func (x *Settings) GetFontColor() string {
	if x != nil {
		return x.FontColor
	}
	return ""
}

func (x *Settings) GetFontFamily() string {
	if x != nil {
		return x.FontFamily
	}
	return ""
}

type Settings_Late struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	DisplayBrbTime bool                   `protobuf:"varint,3,opt,name=display_brb_time,json=displayBrbTime,proto3" json:"display_brb_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Settings_Late) Reset() {
	*x = Settings_Late{}
	mi := &file_messages_overlays_be_right_back_overlays_be_right_back_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings_Late) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings_Late) ProtoMessage() {}

func (x *Settings_Late) ProtoReflect() protoreflect.Message {
	mi := &file_messages_overlays_be_right_back_overlays_be_right_back_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings_Late.ProtoReflect.Descriptor instead.
func (*Settings_Late) Descriptor() ([]byte, []int) {
	return file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Settings_Late) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Settings_Late) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Settings_Late) GetDisplayBrbTime() bool {
	if x != nil {
		return x.DisplayBrbTime
	}
	return false
}

var File_messages_overlays_be_right_back_overlays_be_right_back_proto protoreflect.FileDescriptor

const file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDesc = "" +
	"\n" +
	"<messages/overlays_be_right_back/overlays_be_right_back.proto\x12\x1fmessages.overlays_be_right_back\"\xca\x02\n" +
	"\bSettings\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12B\n" +
	"\x04late\x18\x02 \x01(\v2..messages.overlays_be_right_back.Settings.LateR\x04late\x12)\n" +
	"\x10background_color\x18\x03 \x01(\tR\x0fbackgroundColor\x12\x1b\n" +
	"\tfont_size\x18\x04 \x01(\x05R\bfontSize\x12\x1d\n" +
	"\n" +
	"font_color\x18\x05 \x01(\tR\tfontColor\x12\x1f\n" +
	"\vfont_family\x18\x06 \x01(\tR\n" +
	"fontFamily\x1a^\n" +
	"\x04Late\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12(\n" +
	"\x10display_brb_time\x18\x03 \x01(\bR\x0edisplayBrbTimeBBZ@github.com/twirapp/twir/libs/api/messages/overlays_be_right_backb\x06proto3"

var (
	file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescOnce sync.Once
	file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescData []byte
)

func file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescGZIP() []byte {
	file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescOnce.Do(func() {
		file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDesc), len(file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDesc)))
	})
	return file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDescData
}

var file_messages_overlays_be_right_back_overlays_be_right_back_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messages_overlays_be_right_back_overlays_be_right_back_proto_goTypes = []any{
	(*Settings)(nil),      // 0: messages.overlays_be_right_back.Settings
	(*Settings_Late)(nil), // 1: messages.overlays_be_right_back.Settings.Late
}
var file_messages_overlays_be_right_back_overlays_be_right_back_proto_depIdxs = []int32{
	1, // 0: messages.overlays_be_right_back.Settings.late:type_name -> messages.overlays_be_right_back.Settings.Late
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messages_overlays_be_right_back_overlays_be_right_back_proto_init() }
func file_messages_overlays_be_right_back_overlays_be_right_back_proto_init() {
	if File_messages_overlays_be_right_back_overlays_be_right_back_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDesc), len(file_messages_overlays_be_right_back_overlays_be_right_back_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_overlays_be_right_back_overlays_be_right_back_proto_goTypes,
		DependencyIndexes: file_messages_overlays_be_right_back_overlays_be_right_back_proto_depIdxs,
		MessageInfos:      file_messages_overlays_be_right_back_overlays_be_right_back_proto_msgTypes,
	}.Build()
	File_messages_overlays_be_right_back_overlays_be_right_back_proto = out.File
	file_messages_overlays_be_right_back_overlays_be_right_back_proto_goTypes = nil
	file_messages_overlays_be_right_back_overlays_be_right_back_proto_depIdxs = nil
}
