package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/gql/gqlmodel"
)

// IntegrationsGetServiceAuthLink is the resolver for the integrationsGetServiceAuthLink field.
func (r *queryResolver) IntegrationsGetServiceAuthLink(
	ctx context.Context,
	service gqlmodel.IntegrationService,
) (string, error) {
	panic(fmt.Errorf("not implemented: IntegrationsGetServiceAuthLink - integrationsGetServiceAuthLink"))
}

// IntegrationsGetData is the resolver for the integrationsGetData field.
func (r *queryResolver) IntegrationsGetData(
	ctx context.Context,
	service gqlmodel.IntegrationService,
) (gqlmodel.IntegrationData, error) {
	panic(fmt.Errorf("not implemented: IntegrationsGetData - integrationsGetData"))
}
