apiVersion: 1

prune: true

datasources:
  - name: Uptrace Tempo
    uid: uptrace-tempo
    type: tempo
    access: proxy
    url: http://uptrace/api/tempo/1
    editable: false
    jsonData:
      httpHeaderName1: Authorization
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: uptrace-prometheus
    secureJsonData:
      httpHeaderValue1: ${UPTRACE_PROJECT_TOKEN}

  - name: Uptrace Prometheus
    uid: uptrace-prometheus
    type: prometheus
    access: proxy
    url: http://uptrace/api/prometheus/1
    editable: false
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      httpMethod: POST
    secureJsonData:
      httpHeaderValue1: ${UPTRACE_PROJECT_TOKEN}
