// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package baseapp

import (
	"github.com/twirapp/twir/libs/baseapp/lifecycle"
	"github.com/twirapp/twir/libs/config"
)

// Injectors from wire.go:

func NewBase(opts Opts) (Base, error) {
	lifecycleLifecycle := lifecycle.New()
	config := cfg.NewFx()
	baseappServiceName := provideServiceName(opts)
	tracer := newTracer(config, baseappServiceName, lifecycleLifecycle)
	client, err := newRedis(config)
	if err != nil {
		return Base{}, err
	}
	pool, err := createPgxPool(config)
	if err != nil {
		return Base{}, err
	}
	manager, err := newTransactionManager(pool)
	if err != nil {
		return Base{}, err
	}
	db, err := newGorm(config, lifecycleLifecycle, pool)
	if err != nil {
		return Base{}, err
	}
	clickhouseClient, err := newClickHouse(config, baseappServiceName)
	if err != nil {
		return Base{}, err
	}
	bus, err := newBus(config, baseappServiceName)
	if err != nil {
		return Base{}, err
	}
	pubSub := newAuditPubSub(bus, lifecycleLifecycle)
	repository := newAuditRepository(clickhouseClient)
	recorder := newAuditRecorder(repository, pubSub)
	kv := newKV(client)
	logger := newLogger(baseappServiceName)
	sentryClient, err := newSentry(config, baseappServiceName, lifecycleLifecycle)
	if err != nil {
		return Base{}, err
	}
	reporter, err := newUptimeReporter(client, baseappServiceName, lifecycleLifecycle)
	if err != nil {
		return Base{}, err
	}
	base := newBase(lifecycleLifecycle, config, tracer, client, pool, manager, db, clickhouseClient, bus, pubSub, repository, recorder, kv, logger, sentryClient, reporter)
	return base, nil
}
