<script setup lang="ts">
import type { ItemWithId } from '@twir/grpc/generated/api/api/moderation';
import { NTransfer, NDivider } from 'naive-ui';

defineProps<{
	item: ItemWithId
}>();

const availableLanguages = {
  ABKHAZIAN: 'ab',
  AFAR: 'aa',
  AFRIKAANS: 'af',
  AKAN: 'ak',
  ALBANIAN: 'sq',
  AMHARIC: 'am',
  ARABIC: 'ar',
  ARMENIAN: 'hy',
  ASSAMESE: 'as',
  AYMARA: 'ay',
  AZERBAIJANI: 'az',
  BASHKIR: 'ba',
  BASQUE: 'eu',
  BELARUSIAN: 'be',
  BENGALI: 'bn',
  BIHARI: 'bh',
  BISLAMA: 'bi',
  BOSNIAN: 'bs',
  BRETON: 'br',
  BULGARIAN: 'bg',
  BURMESE: 'my',
  CATALAN: 'ca',
  CEBUANO: 'ceb',
  CHEROKEE: 'chr',
  NYANJA: 'ny',
  CORSICAN: 'co',
  CROATIAN: 'hr',
  CZECH: 'cs',
  Chinese: 'zh',
  ChineseT: 'zh-Hant',
  DANISH: 'da',
  DHIVEHI: 'dv',
  DUTCH: 'nl',
  DZONGKHA: 'dz',
  ENGLISH: 'en',
  ESPERANTO: 'eo',
  ESTONIAN: 'et',
  EWE: 'ee',
  FAROESE: 'fo',
  FIJIAN: 'fj',
  FINNISH: 'fi',
  FRENCH: 'fr',
  FRISIAN: 'fy',
  GA: 'gaa',
  GALICIAN: 'gl',
  GANDA: 'lg',
  GEORGIAN: 'ka',
  GERMAN: 'de',
  GREEK: 'el',
  GREENLANDIC: 'kl',
  GUARANI: 'gn',
  GUJARATI: 'gu',
  HAITIAN_CREOLE: 'ht',
  HAUSA: 'ha',
  HAWAIIAN: 'haw',
  HEBREW: 'iw',
  HINDI: 'hi',
  HMONG: 'hmn',
  HUNGARIAN: 'hu',
  ICELANDIC: 'is',
  IGBO: 'ig',
  INDONESIAN: 'id',
  INTERLINGUA: 'ia',
  INTERLINGUE: 'ie',
  INUKTITUT: 'iu',
  INUPIAK: 'ik',
  IRISH: 'ga',
  ITALIAN: 'it',
  Ignore: 'xxx',
  JAVANESE: 'jw',
  Japanese: 'ja',
  KANNADA: 'kn',
  KASHMIRI: 'ks',
  KAZAKH: 'kk',
  KHASI: 'kha',
  KHMER: 'km',
  KINYARWANDA: 'rw',
  KRIO: 'kri',
  KURDISH: 'ku',
  KYRGYZ: 'ky',
  Korean: 'ko',
  LAOTHIAN: 'lo',
  LATIN: 'la',
  LATVIAN: 'lv',
  LIMBU: 'lif',
  LINGALA: 'ln',
  LITHUANIAN: 'lt',
  LOZI: 'loz',
  LUBA_LULUA: 'lua',
  LUO_KENYA_AND_TANZANIA: 'luo',
  LUXEMBOURGISH: 'lb',
  MACEDONIAN: 'mk',
  MALAGASY: 'mg',
  MALAY: 'ms',
  MALAYALAM: 'ml',
  MALTESE: 'mt',
  MANX: 'gv',
  MAORI: 'mi',
  MARATHI: 'mr',
  MAURITIAN_CREOLE: 'mfe',
  ROMANIAN: 'ro',
  MONGOLIAN: 'mn',
  MONTENEGRIN: 'sr-ME',
  NAURU: 'na',
  NDEBELE: 'nr',
  NEPALI: 'ne',
  NEWARI: 'new',
  NORWEGIAN: 'no',
  NORWEGIAN_N: 'nn',
  OCCITAN: 'oc',
  ORIYA: 'or',
  OROMO: 'om',
  OSSETIAN: 'os',
  PAMPANGA: 'pam',
  PASHTO: 'ps',
  PEDI: 'nso',
  PERSIAN: 'fa',
  POLISH: 'pl',
  PORTUGUESE: 'pt',
  PUNJABI: 'pa',
  QUECHUA: 'qu',
  RAJASTHANI: 'raj',
  RHAETO_ROMANCE: 'rm',
  RUNDI: 'rn',
  RUSSIAN: 'ru',
  SAMOAN: 'sm',
  SANGO: 'sg',
  SANSKRIT: 'sa',
  SCOTS: 'sco',
  SCOTS_GAELIC: 'gd',
  SERBIAN: 'sr',
  SESELWA: 'crs',
  SESOTHO: 'st',
  SHONA: 'sn',
  SINDHI: 'sd',
  SINHALESE: 'si',
  SISWANT: 'ss',
  SLOVAK: 'sk',
  SLOVENIAN: 'sl',
  SOMALI: 'so',
  SPANISH: 'es',
  SUNDANESE: 'su',
  SWAHILI: 'sw',
  SWEDISH: 'sv',
  SYRIAC: 'syr',
  TAGALOG: 'tl',
  TAJIK: 'tg',
  TAMIL: 'ta',
  TATAR: 'tt',
  TELUGU: 'te',
  THAI: 'th',
  TIBETAN: 'bo',
  TIGRINYA: 'ti',
  TONGA: 'to',
  TSONGA: 'ts',
  TSWANA: 'tn',
  TUMBUKA: 'tum',
  TURKISH: 'tr',
  TURKMEN: 'tk',
  TWI: 'tw',
  UIGHUR: 'ug',
  UKRAINIAN: 'uk',
  URDU: 'ur',
  UZBEK: 'uz',
  VENDA: 've',
  VIETNAMESE: 'vi',
  VOLAPUK: 'vo',
  WARAY_PHILIPPINES: 'war',
  WELSH: 'cy',
  WOLOF: 'wo',
  XHOSA: 'xh',
};

const transferOptions = Object.entries(availableLanguages).map(([key, value]) => {
	key = key.toLowerCase();
	key = key.charAt(0).toLocaleUpperCase() + key.slice(1);
	key = key.replaceAll('_', ' ');

	return {
		label: key.charAt(0).toLocaleUpperCase() + key.slice(1),
		value: value,
	};
});
</script>

<template>
	<div>
		<n-transfer
			ref="transfer"
			v-model:value="item.data!.deniedChatLanguages"
			:show-selected="false"
			virtual-scroll
			:options="transferOptions"
			source-filterable
			target-filterable
			source-title="Allowed languages"
			target-title="Disallowed languages"
			source-filter-placeholder="Search"
			target-filter-placeholder="Search"
		/>

		<n-divider style="margin: 0; padding: 0" />
	</div>
</template>
