/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,generate_dependencies,eslint_disable,server_none
// @generated from protobuf file "messages/twitch_protected/twitch_protected.proto" (package "messages.twitch_protected", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message messages.twitch_protected.SearchCategoriesRequest
 */
export interface SearchCategoriesRequest {
    /**
     * @generated from protobuf field: string query = 1;
     */
    query: string;
}
/**
 * @generated from protobuf message messages.twitch_protected.GetCategoriesRequest
 */
export interface GetCategoriesRequest {
    /**
     * @generated from protobuf field: repeated string ids = 1;
     */
    ids: string[];
}
/**
 * @generated from protobuf message messages.twitch_protected.SearchCategoriesResponse
 */
export interface SearchCategoriesResponse {
    /**
     * @generated from protobuf field: repeated messages.twitch_protected.SearchCategoriesResponse.Category categories = 1;
     */
    categories: SearchCategoriesResponse_Category[];
}
/**
 * @generated from protobuf message messages.twitch_protected.SearchCategoriesResponse.Category
 */
export interface SearchCategoriesResponse_Category {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string image = 3;
     */
    image: string;
}
/**
 * @generated from protobuf message messages.twitch_protected.SetChannelInformationRequest
 */
export interface SetChannelInformationRequest {
    /**
     * @generated from protobuf field: string category_id = 1;
     */
    categoryId: string;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SearchCategoriesRequest$Type extends MessageType<SearchCategoriesRequest> {
    constructor() {
        super("messages.twitch_protected.SearchCategoriesRequest", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.twitch_protected.SearchCategoriesRequest
 */
export const SearchCategoriesRequest = new SearchCategoriesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCategoriesRequest$Type extends MessageType<GetCategoriesRequest> {
    constructor() {
        super("messages.twitch_protected.GetCategoriesRequest", [
            { no: 1, name: "ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.twitch_protected.GetCategoriesRequest
 */
export const GetCategoriesRequest = new GetCategoriesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchCategoriesResponse$Type extends MessageType<SearchCategoriesResponse> {
    constructor() {
        super("messages.twitch_protected.SearchCategoriesResponse", [
            { no: 1, name: "categories", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SearchCategoriesResponse_Category }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.twitch_protected.SearchCategoriesResponse
 */
export const SearchCategoriesResponse = new SearchCategoriesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchCategoriesResponse_Category$Type extends MessageType<SearchCategoriesResponse_Category> {
    constructor() {
        super("messages.twitch_protected.SearchCategoriesResponse.Category", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "image", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.twitch_protected.SearchCategoriesResponse.Category
 */
export const SearchCategoriesResponse_Category = new SearchCategoriesResponse_Category$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetChannelInformationRequest$Type extends MessageType<SetChannelInformationRequest> {
    constructor() {
        super("messages.twitch_protected.SetChannelInformationRequest", [
            { no: 1, name: "category_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.twitch_protected.SetChannelInformationRequest
 */
export const SetChannelInformationRequest = new SetChannelInformationRequest$Type();
