extend type Subscription {
	sevenTvData: SevenTvIntegration! @isAuthenticated @hasAccessToSelectedDashboard @hasChannelRolesDashboardPermission(permission: VIEW_INTEGRATIONS)
}

extend type Mutation {
	sevenTvUpdate(input: SevenTvUpdateInput!): Boolean! @isAuthenticated @hasAccessToSelectedDashboard @hasChannelRolesDashboardPermission(permission: MANAGE_INTEGRATIONS)
}

type SevenTvProfile {
	id: String!
	username: String!
	displayName: String!
	avatarUri: String!
}

type SevenTvIntegration {
	isEditor: Boolean!
	botSeventvProfile: SevenTvProfile!
	userSeventvProfile: SevenTvProfile!
	rewardIdForAddEmote: String
	rewardIdForRemoveEmote: String
	emoteSetId: String
	deleteEmotesOnlyAddedByApp: Boolean!
}

input SevenTvUpdateInput {
	rewardIdForAddEmote: String
	rewardIdForRemoveEmote: String
	deleteEmotesOnlyAddedByApp: Boolean!
}
