extend type Subscription {
	dashboardStats: DashboardStats! @isAuthenticated
	botStatus: BotStatus! @isAuthenticated
	botStatuses: [BotStatus!]! @isAuthenticated
}

extend type Mutation {
	botJoinLeave(action: BotJoinLeaveAction!, dashboardId: String, platform: String): Boolean! @isAuthenticated
}

type DashboardStats {
	categoryId: ID!
	categoryName: String!
	viewers: Int
	startedAt: Time
	title: String!
	chatMessages: Int!
	followers: Int!
	usedEmotes: Int!
	requestedSongs: Int!
	subs: Int!
	platforms: [DashboardPlatformStats!]!
}

type DashboardPlatformStats {
	platform: Platform!
	isLive: Boolean!
	title: String
	categoryId: ID
	categoryName: String
	viewers: Int
	followers: Int
	startedAt: Time
	chatMessages: Int!
	usedEmotes: Int!
	canEditInfo: Boolean!
}

type BotStatus {
	dashboardId: String!
	platform: String!
	channelName: String!
	isMod: Boolean!
	botId: String!
	botName: String!
	enabled: Boolean!
}

enum BotJoinLeaveAction {
	JOIN
	LEAVE
}
