apiVersion: 1
datasources:
  - name: VictoriaTraces
    type: jaeger
    access: proxy
    url: http://victoria-traces:10428
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: victoria-logs
        filterByTraceID: true
        filterBySpanID: true
