apiVersion: 1
datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    isDefault: false
    jsonData:
      maxLines: 1000
      logLevelRules:
        - field: "level"
          value: "error"
          level: "error"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "warn"
          level: "warning"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "info"
          level: "info"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "debug"
          level: "debug"
          operator: "equals"
          enabled: true
