import { MigrationInterface, QueryRunner } from "typeorm";

export class addMissedUuid1663342405491 implements MigrationInterface {
    name = 'addMissedUuid1663342405491'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bots" DROP CONSTRAINT "bots_tokenId_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df4240a5d71aa6a23b829d3cee"`);
        await queryRunner.query(`ALTER TABLE "bots" DROP CONSTRAINT "UQ_df4240a5d71aa6a23b829d3cee8"`);
        await queryRunner.query(`ALTER TABLE "bots" DROP COLUMN "tokenId"`);
        await queryRunner.query(`ALTER TABLE "bots" ADD "tokenId" uuid`);
        await queryRunner.query(`ALTER TABLE "bots" ADD CONSTRAINT "UQ_df4240a5d71aa6a23b829d3cee8" UNIQUE ("tokenId")`);
        await queryRunner.query(`ALTER TABLE "channels" DROP CONSTRAINT "FK_4f890144c0cb55fe7867b8f61e6"`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "botId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" DROP CONSTRAINT "FK_b18b2e298e41de0397acea55b97"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" DROP CONSTRAINT "FK_2db68a1b263bea3f214186bb24c"`);
        await queryRunner.query(`ALTER TABLE "channels_commands" DROP CONSTRAINT "channels_commands_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_commands" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_commands" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_commands" ADD CONSTRAINT "PK_6f530d7cee75abfb1ef1cc7e09b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" DROP CONSTRAINT "FK_2bf1744a6cd76e4457eddfd3bc4"`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" DROP CONSTRAINT "channels_customvars_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ADD CONSTRAINT "PK_a6d0167a26c310ef7832c66b55d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ALTER COLUMN "channelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" DROP CONSTRAINT "FK_15402461d2eb224e2e088b35606"`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" DROP CONSTRAINT "channels_greetings_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ADD CONSTRAINT "PK_90ee111c7fefdaaff4918cab6df" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ALTER COLUMN "channelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP CONSTRAINT "FK_c17a48a983ac20ff800f553630a"`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP CONSTRAINT "channels_integrations_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD CONSTRAINT "PK_d5f8b2ee43dbd8f5a68d1ce71ca" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ALTER COLUMN "channelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" DROP CONSTRAINT "channels_keywords_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" ADD CONSTRAINT "PK_6cb4cb2b8a95cc2728d1feab106" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" DROP CONSTRAINT "channels_moderation_settings_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" ADD CONSTRAINT "PK_fc3b021f2a7a5fde68b58543d93" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP CONSTRAINT "FK_b7e83e12e0482fa968de97b6b06"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP CONSTRAINT "FK_6bb136710060aa1be1744bc3bc9"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP CONSTRAINT "channels_permits_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD CONSTRAINT "PK_1e24b77c350a387af97801f64ae" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ALTER COLUMN "channelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_timers" DROP CONSTRAINT "FK_50978b1848b99458d6ceb6b1989"`);
        await queryRunner.query(`ALTER TABLE "channels_timers" DROP CONSTRAINT "channels_timers_pkey"`);
        await queryRunner.query(`ALTER TABLE "channels_timers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ADD CONSTRAINT "PK_858789b56e6e0956593768f9e05" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ALTER COLUMN "channelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" DROP COLUMN "commandId"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" ADD "commandId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" DROP CONSTRAINT "FK_14be9e16eaece94af10d56044e0"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" DROP COLUMN "commandId"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ADD "commandId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" DROP CONSTRAINT "FK_82931b7f57c891fd7da375f3892"`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" DROP CONSTRAINT "FK_0ad4bccf63566cd4792dfe9f191"`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ALTER COLUMN "channelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dota_matches_cards" DROP CONSTRAINT "FK_a9d58830e97acdda53124a0431f"`);
        await queryRunner.query(`ALTER TABLE "dota_matches" DROP CONSTRAINT "FK_7fa32afcc462ae6f50b176f6c9c"`);
        await queryRunner.query(`ALTER TABLE "dota_matches" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "dota_matches" ALTER COLUMN "gameModeId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dota_matches_cards" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "dota_matches_results" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP CONSTRAINT "FK_4958a98d1c19453c5755a422906"`);
        await queryRunner.query(`ALTER TABLE "integrations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" DROP CONSTRAINT "FK_f5d19d90314d14d636752e2888b"`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" DROP CONSTRAINT "FK_4bfdb54ebcde220bcbcf696d862"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" ALTER COLUMN "notificationId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_d98a275f8bc6cd986fcbe2eab01"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "tokens_pkey"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d98a275f8bc6cd986fcbe2eab0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_d98a275f8bc6cd986fcbe2eab01"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "tokenId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "tokenId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_d98a275f8bc6cd986fcbe2eab01" UNIQUE ("tokenId")`);
        await queryRunner.query(`ALTER TABLE "users_files" DROP CONSTRAINT "FK_74cae0ea1fbb3df84c488ec0383"`);
        await queryRunner.query(`ALTER TABLE "users_files" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "users_files" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_stats" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" DROP CONSTRAINT "FK_8d7e1a04a0d2d9868192561952d"`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ALTER COLUMN "notificationId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_df4240a5d71aa6a23b829d3cee" ON "bots" ("tokenId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d98a275f8bc6cd986fcbe2eab0" ON "users" ("tokenId") `);
        await queryRunner.query(`ALTER TABLE "bots" ADD CONSTRAINT "bots_tokenId_key" FOREIGN KEY ("tokenId") REFERENCES "tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels" ADD CONSTRAINT "FK_4f890144c0cb55fe7867b8f61e6" FOREIGN KEY ("botId") REFERENCES "bots"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ADD CONSTRAINT "FK_2bf1744a6cd76e4457eddfd3bc4" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ADD CONSTRAINT "FK_15402461d2eb224e2e088b35606" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD CONSTRAINT "FK_c17a48a983ac20ff800f553630a" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD CONSTRAINT "FK_4958a98d1c19453c5755a422906" FOREIGN KEY ("integrationId") REFERENCES "integrations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD CONSTRAINT "FK_b7e83e12e0482fa968de97b6b06" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD CONSTRAINT "FK_6bb136710060aa1be1744bc3bc9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ADD CONSTRAINT "FK_50978b1848b99458d6ceb6b1989" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" ADD CONSTRAINT "FK_b18b2e298e41de0397acea55b97" FOREIGN KEY ("commandId") REFERENCES "channels_commands"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ADD CONSTRAINT "FK_2db68a1b263bea3f214186bb24c" FOREIGN KEY ("commandId") REFERENCES "channels_commands"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ADD CONSTRAINT "FK_14be9e16eaece94af10d56044e0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ADD CONSTRAINT "FK_82931b7f57c891fd7da375f3892" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ADD CONSTRAINT "FK_0ad4bccf63566cd4792dfe9f191" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dota_matches" ADD CONSTRAINT "FK_7fa32afcc462ae6f50b176f6c9c" FOREIGN KEY ("gameModeId") REFERENCES "dota_game_modes"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dota_matches_cards" ADD CONSTRAINT "FK_a9d58830e97acdda53124a0431f" FOREIGN KEY ("match_id") REFERENCES "dota_matches"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" ADD CONSTRAINT "FK_4bfdb54ebcde220bcbcf696d862" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_d98a275f8bc6cd986fcbe2eab01" FOREIGN KEY ("tokenId") REFERENCES "tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_files" ADD CONSTRAINT "FK_74cae0ea1fbb3df84c488ec0383" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ADD CONSTRAINT "FK_f5d19d90314d14d636752e2888b" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ADD CONSTRAINT "FK_8d7e1a04a0d2d9868192561952d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" DROP CONSTRAINT "FK_8d7e1a04a0d2d9868192561952d"`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" DROP CONSTRAINT "FK_f5d19d90314d14d636752e2888b"`);
        await queryRunner.query(`ALTER TABLE "users_files" DROP CONSTRAINT "FK_74cae0ea1fbb3df84c488ec0383"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_d98a275f8bc6cd986fcbe2eab01"`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" DROP CONSTRAINT "FK_4bfdb54ebcde220bcbcf696d862"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "dota_matches_cards" DROP CONSTRAINT "FK_a9d58830e97acdda53124a0431f"`);
        await queryRunner.query(`ALTER TABLE "dota_matches" DROP CONSTRAINT "FK_7fa32afcc462ae6f50b176f6c9c"`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" DROP CONSTRAINT "FK_0ad4bccf63566cd4792dfe9f191"`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" DROP CONSTRAINT "FK_82931b7f57c891fd7da375f3892"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" DROP CONSTRAINT "FK_14be9e16eaece94af10d56044e0"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" DROP CONSTRAINT "FK_2db68a1b263bea3f214186bb24c"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" DROP CONSTRAINT "FK_b18b2e298e41de0397acea55b97"`);
        await queryRunner.query(`ALTER TABLE "channels_timers" DROP CONSTRAINT "FK_50978b1848b99458d6ceb6b1989"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP CONSTRAINT "FK_6bb136710060aa1be1744bc3bc9"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP CONSTRAINT "FK_b7e83e12e0482fa968de97b6b06"`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP CONSTRAINT "FK_4958a98d1c19453c5755a422906"`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP CONSTRAINT "FK_c17a48a983ac20ff800f553630a"`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" DROP CONSTRAINT "FK_15402461d2eb224e2e088b35606"`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" DROP CONSTRAINT "FK_2bf1744a6cd76e4457eddfd3bc4"`);
        await queryRunner.query(`ALTER TABLE "channels" DROP CONSTRAINT "FK_4f890144c0cb55fe7867b8f61e6"`);
        await queryRunner.query(`ALTER TABLE "bots" DROP CONSTRAINT "bots_tokenId_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d98a275f8bc6cd986fcbe2eab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df4240a5d71aa6a23b829d3cee"`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ALTER COLUMN "notificationId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ADD CONSTRAINT "FK_8d7e1a04a0d2d9868192561952d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_stats" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "users_files" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_files" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "users_files" ADD CONSTRAINT "FK_74cae0ea1fbb3df84c488ec0383" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_d98a275f8bc6cd986fcbe2eab01"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "tokenId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "tokenId" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_d98a275f8bc6cd986fcbe2eab01" UNIQUE ("tokenId")`);
        await queryRunner.query(`CREATE INDEX "IDX_d98a275f8bc6cd986fcbe2eab0" ON "users" ("tokenId") `);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "PK_3001e89ada36263dabf1fb6210a"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "tokens_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_d98a275f8bc6cd986fcbe2eab01" FOREIGN KEY ("tokenId") REFERENCES "tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" ALTER COLUMN "notificationId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notifications_messages" ADD CONSTRAINT "FK_4bfdb54ebcde220bcbcf696d862" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_viewed_notifications" ADD CONSTRAINT "FK_f5d19d90314d14d636752e2888b" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "integrations" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD CONSTRAINT "FK_4958a98d1c19453c5755a422906" FOREIGN KEY ("integrationId") REFERENCES "integrations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dota_matches_results" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "dota_matches_cards" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "dota_matches" ALTER COLUMN "gameModeId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dota_matches" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "dota_matches" ADD CONSTRAINT "FK_7fa32afcc462ae6f50b176f6c9c" FOREIGN KEY ("gameModeId") REFERENCES "dota_game_modes"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dota_matches_cards" ADD CONSTRAINT "FK_a9d58830e97acdda53124a0431f" FOREIGN KEY ("match_id") REFERENCES "dota_matches"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ALTER COLUMN "channelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ADD CONSTRAINT "FK_0ad4bccf63566cd4792dfe9f191" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_dashboard_access" ADD CONSTRAINT "FK_82931b7f57c891fd7da375f3892" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" DROP COLUMN "commandId"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ADD "commandId" text`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ADD CONSTRAINT "FK_14be9e16eaece94af10d56044e0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" DROP COLUMN "commandId"`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" ADD "commandId" text`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" ALTER COLUMN "id" SET DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ALTER COLUMN "channelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_timers" DROP CONSTRAINT "PK_858789b56e6e0956593768f9e05"`);
        await queryRunner.query(`ALTER TABLE "channels_timers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ADD CONSTRAINT "channels_timers_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_timers" ADD CONSTRAINT "FK_50978b1848b99458d6ceb6b1989" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ALTER COLUMN "channelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP CONSTRAINT "PK_1e24b77c350a387af97801f64ae"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD CONSTRAINT "channels_permits_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD CONSTRAINT "FK_6bb136710060aa1be1744bc3bc9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_permits" ADD CONSTRAINT "FK_b7e83e12e0482fa968de97b6b06" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" DROP CONSTRAINT "PK_fc3b021f2a7a5fde68b58543d93"`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_moderation_settings" ADD CONSTRAINT "channels_moderation_settings_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" DROP CONSTRAINT "PK_6cb4cb2b8a95cc2728d1feab106"`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_keywords" ADD CONSTRAINT "channels_keywords_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ALTER COLUMN "channelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP CONSTRAINT "PK_d5f8b2ee43dbd8f5a68d1ce71ca"`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD CONSTRAINT "channels_integrations_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_integrations" ADD CONSTRAINT "FK_c17a48a983ac20ff800f553630a" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ALTER COLUMN "channelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" DROP CONSTRAINT "PK_90ee111c7fefdaaff4918cab6df"`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ADD CONSTRAINT "channels_greetings_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_greetings" ADD CONSTRAINT "FK_15402461d2eb224e2e088b35606" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ALTER COLUMN "channelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" DROP CONSTRAINT "PK_a6d0167a26c310ef7832c66b55d"`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ADD CONSTRAINT "channels_customvars_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_customvars" ADD CONSTRAINT "FK_2bf1744a6cd76e4457eddfd3bc4" FOREIGN KEY ("channelId") REFERENCES "channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_commands" DROP CONSTRAINT "PK_6f530d7cee75abfb1ef1cc7e09b"`);
        await queryRunner.query(`ALTER TABLE "channels_commands" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "channels_commands" ADD "id" text NOT NULL DEFAULT 'gen_random_uuid()'`);
        await queryRunner.query(`ALTER TABLE "channels_commands" ADD CONSTRAINT "channels_commands_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "channels_commands_usages" ADD CONSTRAINT "FK_2db68a1b263bea3f214186bb24c" FOREIGN KEY ("commandId") REFERENCES "channels_commands"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_commands_responses" ADD CONSTRAINT "FK_b18b2e298e41de0397acea55b97" FOREIGN KEY ("commandId") REFERENCES "channels_commands"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "botId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ADD CONSTRAINT "FK_4f890144c0cb55fe7867b8f61e6" FOREIGN KEY ("botId") REFERENCES "bots"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bots" DROP CONSTRAINT "UQ_df4240a5d71aa6a23b829d3cee8"`);
        await queryRunner.query(`ALTER TABLE "bots" DROP COLUMN "tokenId"`);
        await queryRunner.query(`ALTER TABLE "bots" ADD "tokenId" text`);
        await queryRunner.query(`ALTER TABLE "bots" ADD CONSTRAINT "UQ_df4240a5d71aa6a23b829d3cee8" UNIQUE ("tokenId")`);
        await queryRunner.query(`CREATE INDEX "IDX_df4240a5d71aa6a23b829d3cee" ON "bots" ("tokenId") `);
        await queryRunner.query(`ALTER TABLE "bots" ADD CONSTRAINT "bots_tokenId_key" FOREIGN KEY ("tokenId") REFERENCES "tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
    }

}
