/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,generate_dependencies,eslint_disable,server_none
// @generated from protobuf file "messages/overlays/overlays.proto" (package "messages.overlays", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message messages.overlays.OverlayLayerSettings
 */
export interface OverlayLayerSettings {
    /**
     * @generated from protobuf field: string html_overlay_html = 1;
     */
    htmlOverlayHtml: string;
    /**
     * @generated from protobuf field: string html_overlay_css = 2;
     */
    htmlOverlayCss: string;
    /**
     * @generated from protobuf field: string html_overlay_js = 3;
     */
    htmlOverlayJs: string;
    /**
     * @generated from protobuf field: int32 html_overlay_html_data_poll_seconds_interval = 4;
     */
    htmlOverlayHtmlDataPollSecondsInterval: number;
}
/**
 * @generated from protobuf message messages.overlays.OverlayLayer
 */
export interface OverlayLayer {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: messages.overlays.OverlayLayerType type = 2;
     */
    type: OverlayLayerType;
    /**
     * @generated from protobuf field: messages.overlays.OverlayLayerSettings settings = 3;
     */
    settings?: OverlayLayerSettings;
    /**
     * @generated from protobuf field: string overlay_id = 4;
     */
    overlayId: string;
    /**
     * @generated from protobuf field: int32 pos_x = 5;
     */
    posX: number;
    /**
     * @generated from protobuf field: int32 pos_y = 6;
     */
    posY: number;
    /**
     * @generated from protobuf field: int32 width = 7;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 8;
     */
    height: number;
    /**
     * @generated from protobuf field: string createdAt = 9;
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updatedAt = 10;
     */
    updatedAt: string;
    /**
     * @generated from protobuf field: bool periodically_refetch_data = 11;
     */
    periodicallyRefetchData: boolean;
}
/**
 * @generated from protobuf message messages.overlays.Overlay
 */
export interface Overlay {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string channel_id = 2;
     */
    channelId: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: string createdAt = 4;
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updatedAt = 5;
     */
    updatedAt: string;
    /**
     * @generated from protobuf field: repeated messages.overlays.OverlayLayer layers = 6;
     */
    layers: OverlayLayer[];
    /**
     * @generated from protobuf field: int32 width = 7;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 8;
     */
    height: number;
}
/**
 * @generated from protobuf message messages.overlays.GetByIdRequest
 */
export interface GetByIdRequest {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message messages.overlays.GetAllResponse
 */
export interface GetAllResponse {
    /**
     * @generated from protobuf field: repeated messages.overlays.Overlay overlays = 1;
     */
    overlays: Overlay[];
}
/**
 * @generated from protobuf message messages.overlays.DeleteRequest
 */
export interface DeleteRequest {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message messages.overlays.CreateLayer
 */
export interface CreateLayer {
    /**
     * @generated from protobuf field: messages.overlays.OverlayLayerType type = 1;
     */
    type: OverlayLayerType;
    /**
     * @generated from protobuf field: messages.overlays.OverlayLayerSettings settings = 2;
     */
    settings?: OverlayLayerSettings;
    /**
     * @generated from protobuf field: int32 pos_x = 3;
     */
    posX: number;
    /**
     * @generated from protobuf field: int32 pos_y = 4;
     */
    posY: number;
    /**
     * @generated from protobuf field: int32 width = 5;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 6;
     */
    height: number;
    /**
     * @generated from protobuf field: bool periodically_refetch_data = 7;
     */
    periodicallyRefetchData: boolean;
}
/**
 * @generated from protobuf message messages.overlays.CreateRequest
 */
export interface CreateRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: repeated messages.overlays.CreateLayer layers = 2;
     */
    layers: CreateLayer[];
    /**
     * @generated from protobuf field: int32 width = 3;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 4;
     */
    height: number;
}
/**
 * @generated from protobuf message messages.overlays.UpdateRequest
 */
export interface UpdateRequest {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: repeated messages.overlays.CreateLayer layers = 3;
     */
    layers: CreateLayer[];
    /**
     * @generated from protobuf field: int32 width = 4;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 5;
     */
    height: number;
}
/**
 * @generated from protobuf message messages.overlays.ParseHtmlOverlayRequest
 */
export interface ParseHtmlOverlayRequest {
    /**
     * @generated from protobuf field: string html = 1;
     */
    html: string;
}
/**
 * @generated from protobuf message messages.overlays.ParseHtmlOverlayResponse
 */
export interface ParseHtmlOverlayResponse {
    /**
     * @generated from protobuf field: string html = 1;
     */
    html: string;
}
/**
 * @generated from protobuf enum messages.overlays.OverlayLayerType
 */
export enum OverlayLayerType {
    /**
     * @generated from protobuf enum value: HTML = 0;
     */
    HTML = 0
}
// @generated message type with reflection information, may provide speed optimized methods
class OverlayLayerSettings$Type extends MessageType<OverlayLayerSettings> {
    constructor() {
        super("messages.overlays.OverlayLayerSettings", [
            { no: 1, name: "html_overlay_html", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "html_overlay_css", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "html_overlay_js", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "html_overlay_html_data_poll_seconds_interval", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.OverlayLayerSettings
 */
export const OverlayLayerSettings = new OverlayLayerSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OverlayLayer$Type extends MessageType<OverlayLayer> {
    constructor() {
        super("messages.overlays.OverlayLayer", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["messages.overlays.OverlayLayerType", OverlayLayerType] },
            { no: 3, name: "settings", kind: "message", T: () => OverlayLayerSettings },
            { no: 4, name: "overlay_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "pos_x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "pos_y", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "updatedAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "periodically_refetch_data", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.OverlayLayer
 */
export const OverlayLayer = new OverlayLayer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Overlay$Type extends MessageType<Overlay> {
    constructor() {
        super("messages.overlays.Overlay", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "channel_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "updatedAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "layers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OverlayLayer },
            { no: 7, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.Overlay
 */
export const Overlay = new Overlay$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetByIdRequest$Type extends MessageType<GetByIdRequest> {
    constructor() {
        super("messages.overlays.GetByIdRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.GetByIdRequest
 */
export const GetByIdRequest = new GetByIdRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllResponse$Type extends MessageType<GetAllResponse> {
    constructor() {
        super("messages.overlays.GetAllResponse", [
            { no: 1, name: "overlays", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Overlay }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.GetAllResponse
 */
export const GetAllResponse = new GetAllResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteRequest$Type extends MessageType<DeleteRequest> {
    constructor() {
        super("messages.overlays.DeleteRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.DeleteRequest
 */
export const DeleteRequest = new DeleteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateLayer$Type extends MessageType<CreateLayer> {
    constructor() {
        super("messages.overlays.CreateLayer", [
            { no: 1, name: "type", kind: "enum", T: () => ["messages.overlays.OverlayLayerType", OverlayLayerType] },
            { no: 2, name: "settings", kind: "message", T: () => OverlayLayerSettings },
            { no: 3, name: "pos_x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "pos_y", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "periodically_refetch_data", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.CreateLayer
 */
export const CreateLayer = new CreateLayer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateRequest$Type extends MessageType<CreateRequest> {
    constructor() {
        super("messages.overlays.CreateRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "layers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CreateLayer },
            { no: 3, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.CreateRequest
 */
export const CreateRequest = new CreateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateRequest$Type extends MessageType<UpdateRequest> {
    constructor() {
        super("messages.overlays.UpdateRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "layers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CreateLayer },
            { no: 4, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.UpdateRequest
 */
export const UpdateRequest = new UpdateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ParseHtmlOverlayRequest$Type extends MessageType<ParseHtmlOverlayRequest> {
    constructor() {
        super("messages.overlays.ParseHtmlOverlayRequest", [
            { no: 1, name: "html", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.ParseHtmlOverlayRequest
 */
export const ParseHtmlOverlayRequest = new ParseHtmlOverlayRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ParseHtmlOverlayResponse$Type extends MessageType<ParseHtmlOverlayResponse> {
    constructor() {
        super("messages.overlays.ParseHtmlOverlayResponse", [
            { no: 1, name: "html", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message messages.overlays.ParseHtmlOverlayResponse
 */
export const ParseHtmlOverlayResponse = new ParseHtmlOverlayResponse$Type();
