// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/twirapp/twir/apps/timers/app"
	"github.com/twirapp/twir/apps/timers/internal/bus-listener"
	"github.com/twirapp/twir/apps/timers/internal/manager"
	"github.com/twirapp/twir/libs/baseapp"
	"github.com/twirapp/twir/libs/cache/channel"
	pgx2 "github.com/twirapp/twir/libs/repositories/channels/pgx"
	"github.com/twirapp/twir/libs/repositories/streams/datasource/postgres"
	"github.com/twirapp/twir/libs/repositories/timers/pgx"
	"github.com/twirapp/twir/libs/services/channels"
)

// Injectors from wire.go:

func initializeApplication() (*app.Application, error) {
	opts := _wireOptsValue
	base, err := baseapp.NewBase(opts)
	if err != nil {
		return nil, err
	}
	lifecycle := base.Lifecycle
	logger := base.Logger
	bus := base.Bus
	pool := base.PgxPool
	pgxPgx := pgx.NewFx(pool)
	pgx3 := pgx2.NewFx(pool)
	kv := base.KV
	genericCacher := channel.New(pgx3, kv)
	client := base.Redis
	config := base.Config
	postgresPgx := postgres.NewFx(pool)
	channelService := channelservice.NewChannelService(pgx3, bus, config, kv, postgresPgx)
	managerOpts := manager.Opts{
		LC:                lifecycle,
		Repository:        pgxPgx,
		Logger:            logger,
		ChannelCachedRepo: genericCacher,
		Redis:             client,
		TwirBus:           bus,
		Config:            config,
		ChannelsRepo:      pgx3,
		ChannelsService:   channelService,
	}
	managerManager := manager.New(managerOpts)
	bus_listenerOpts := bus_listener.Opts{
		Lc:      lifecycle,
		Logger:  logger,
		Bus:     bus,
		Manager: managerManager,
	}
	application, err := app.NewApplication(lifecycle, logger, bus_listenerOpts)
	if err != nil {
		return nil, err
	}
	return application, nil
}

var (
	_wireOptsValue = baseapp.Opts{AppName: app.Service}
)
