package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	platformentity "github.com/twirapp/twir/libs/entities/platform"
	channelservice "github.com/twirapp/twir/libs/services/channels"
)

// ChannelBySlug is the resolver for the channelBySlug field.
func (r *queryResolver) ChannelBySlug(ctx context.Context, channelName string, platform *gqlmodel.Platform) (*gqlmodel.TwirPublicUser, error) {
	var plat *platformentity.Platform
	if platform != nil {
		p, err := mappers.GraphQLPlatformToEntity(*platform)
		if err != nil {
			return nil, err
		}

		plat = &p
	}

	ch, err := r.deps.ChannelService.GetBySlug(
		ctx, channelservice.GetBySlugOpts{
			Slug:     channelName,
			Platform: plat,
		},
	)
	if err != nil {
		return nil, err
	}

	return mappers.MapChannelModelToGqlPublicUser(ch), nil
}
