package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/google/uuid"
	data_loader "github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/dataloader"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlerrors"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/graph"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	platformentity "github.com/twirapp/twir/libs/entities/platform"
	model "github.com/twirapp/twir/libs/gomodels"
	"github.com/twirapp/twir/libs/logger"
)

// TwitchProfile is the resolver for the twitchProfile field.
func (r *communityUserResolver) TwitchProfile(ctx context.Context, obj *gqlmodel.CommunityUser) (*gqlmodel.TwirUserTwitchInfo, error) {
	if obj.Platform != gqlmodel.PlatformTwitch || obj.PlatformID == "" {
		return nil, nil
	}

	return data_loader.GetHelixUserById(ctx, obj.PlatformID)
}

// CommunityResetStats is the resolver for the communityResetStats field.
func (r *mutationResolver) CommunityResetStats(ctx context.Context, typeArg gqlmodel.CommunityUsersResetType) (bool, error) {
	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	dashboardId, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	var channel model.Channels
	if err := r.deps.Gorm.WithContext(ctx).Where("id = ?", dashboardId).First(&channel).Error; err != nil {
		return false, gqlerrors.HandleError(err)
	}

	if !channel.IsOwner(user.ID) {
		return false, fmt.Errorf("you cannot reset stats for this user")
	}

	var field string

	switch typeArg {
	case gqlmodel.CommunityUsersResetTypeMessages:
		field = "messages"
	case gqlmodel.CommunityUsersResetTypeWatched:
		field = "watched"
	case gqlmodel.CommunityUsersResetTypeUsedChannelsPoints:
		field = "usedChannelPoints"
	case gqlmodel.CommunityUsersResetTypeUsedEmotes:
		field = "emotes"
	}

	if field == "" {
		return false, fmt.Errorf("unknown reset typeArg: %s", typeArg)
	}

	err = r.deps.Gorm.WithContext(ctx).
		Model(&model.UsersStats{}).
		Where(`channel_id = ?`, dashboardId).
		Update(field, 0).Error
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// CommunityUsers is the resolver for the communityUsers field.
func (r *queryResolver) CommunityUsers(ctx context.Context, opts gqlmodel.CommunityUsersOpts) (*gqlmodel.CommunityUsersResponse, error) {
	var page int
	perPage := 20

	if opts.Page.IsSet() {
		page = *opts.Page.Value()
	}

	if opts.PerPage.IsSet() {
		perPage = *opts.PerPage.Value()
	}

	channelID, err := uuid.Parse(opts.ChannelID)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	channel, err := r.deps.ChannelsRepository.GetByID(ctx, channelID)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	queryBuilder := squirrel.StatementBuilder.PlaceholderFormat(squirrel.Dollar).
		Select(
			`users_stats.*`,
			`users.platform`,
			`users.platform_id`,
			`users.login`,
			`users.display_name`,
			`users.avatar`,
		).
		From("users_stats").
		Join(`users ON users.id = users_stats.user_id`).
		Where(squirrel.Expr(`users_stats.channel_id = ?::uuid`, opts.ChannelID)).
		Where(`NOT EXISTS (SELECT 1 FROM users_ignored ui JOIN users u ON u.platform = 'twitch' AND u.platform_id = ui.id WHERE u.id = users_stats.user_id)`).
		Limit(uint64(perPage)).
		Offset(uint64(page*perPage)).
		GroupBy(`users_stats.id`, `users.platform`, `users.platform_id`, `users.login`, `users.display_name`, `users.avatar`)

	countBuilder := squirrel.StatementBuilder.PlaceholderFormat(squirrel.Dollar).
		Select(`COUNT(DISTINCT users_stats.id)`).
		From("users_stats").
		Join(`users ON users.id = users_stats.user_id`).
		Where(squirrel.Expr(`users_stats.channel_id = ?::uuid`, opts.ChannelID)).
		Where(`NOT EXISTS (SELECT 1 FROM users_ignored ui JOIN users u ON u.platform = 'twitch' AND u.platform_id = ui.id WHERE u.id = users_stats.user_id)`)

	if channel.TwitchUserID != nil {
		queryBuilder = queryBuilder.Where(squirrel.NotEq{`users_stats.user_id`: *channel.TwitchUserID})
		countBuilder = countBuilder.Where(squirrel.NotEq{`users_stats.user_id`: *channel.TwitchUserID})
	}
	if channel.KickUserID != nil {
		queryBuilder = queryBuilder.Where(squirrel.NotEq{`users_stats.user_id`: *channel.KickUserID})
		countBuilder = countBuilder.Where(squirrel.NotEq{`users_stats.user_id`: *channel.KickUserID})
	}
	if channel.KickBotID != nil {
		queryBuilder = queryBuilder.Where(squirrel.NotEq{`users_stats.user_id`: *channel.KickBotID})
		countBuilder = countBuilder.Where(squirrel.NotEq{`users_stats.user_id`: *channel.KickBotID})
	}
	if channel.BotID != "" {
		botFilter := squirrel.Expr(
			`users_stats.user_id NOT IN (SELECT id FROM users WHERE platform_id = ? AND platform = 'twitch')`,
			channel.BotID,
		)
		queryBuilder = queryBuilder.Where(botFilter)
		countBuilder = countBuilder.Where(botFilter)
	}

	if opts.Search.IsSet() {
		searchQuery := "%" + strings.TrimSpace(*opts.Search.Value()) + "%"
		searchFilter := squirrel.Or{
			squirrel.Expr(`users.login ILIKE ?`, searchQuery),
			squirrel.Expr(`users.display_name ILIKE ?`, searchQuery),
			squirrel.Expr(`users.platform_id ILIKE ?`, searchQuery),
		}
		queryBuilder = queryBuilder.Where(searchFilter)
		countBuilder = countBuilder.Where(searchFilter)
	}

	if opts.Platforms.IsSet() {
		platforms, err := mappers.GraphQLPlatformsToEntities(opts.Platforms.Value())
		if err != nil {
			return nil, gqlerrors.HandleError(err)
		}

		if len(platforms) > 0 {
			platformValues := make([]string, 0, len(platforms))
			for _, platform := range platforms {
				platformValues = append(platformValues, platform.String())
			}

			queryBuilder = queryBuilder.Where(squirrel.Eq{"users.platform": platformValues})
			countBuilder = countBuilder.Where(squirrel.Eq{"users.platform": platformValues})
		}
	}

	var sortBy string
	if opts.SortBy.IsSet() {
		switch *opts.SortBy.Value() {
		case gqlmodel.CommunityUsersSortByMessages:
			sortBy = "messages"
		case gqlmodel.CommunityUsersSortByUsedChannelsPoints:
			sortBy = "usedChannelPoints"
		case gqlmodel.CommunityUsersSortByUsedEmotes:
			sortBy = "emotes"
		case gqlmodel.CommunityUsersSortByWatched:
			sortBy = "watched"
		}
	}

	if sortBy != "" && !opts.Order.IsSet() {
		queryBuilder = queryBuilder.
			OrderBy(`users_stats.watched DESC`)
		// GroupBy(`users_stats.watched`)
	} else if sortBy != "" && opts.Order.IsSet() {
		order := *opts.Order.Value()
		queryBuilder = queryBuilder.
			OrderBy(
				fmt.Sprintf(
					`users_stats.%s %s`,
					sortBy,
					strings.ToLower(order.String()),
				),
			)
	}

	query, args, err := queryBuilder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("invalid query on backend: %w", err)
	}

	rows, err := r.deps.Gorm.WithContext(ctx).Raw(query, args...).Rows()
	if err != nil {
		r.deps.Logger.Error(
			"cannot get community users",
			logger.Error(err),
			slog.String("query", query),
			slog.Any("args", args),
		)
		return nil, gqlerrors.HandleError(err)
	}
	defer rows.Close()

	type communityUserRow struct {
		ID                string
		Messages          int32
		Watched           int64
		ChannelID         string
		UserID            string
		UsedChannelPoints int64
		IsMod             bool
		IsVip             bool
		IsSubscriber      bool
		Reputation        int64
		Emotes            int
		CreatedAt         time.Time
		UpdatedAt         time.Time
		Platform          platformentity.Platform
		PlatformID        string
		Login             string
		DisplayName       string
		Avatar            string
	}

	var dbUsers []communityUserRow
	for rows.Next() {
		var dbUser communityUserRow

		err = rows.Scan(
			&dbUser.ID,
			&dbUser.Messages,
			&dbUser.Watched,
			&dbUser.ChannelID,
			&dbUser.UserID,
			&dbUser.UsedChannelPoints,
			&dbUser.IsMod,
			&dbUser.IsVip,
			&dbUser.IsSubscriber,
			&dbUser.Reputation,
			&dbUser.Emotes,
			&dbUser.CreatedAt,
			&dbUser.UpdatedAt,
			&dbUser.Platform,
			&dbUser.PlatformID,
			&dbUser.Login,
			&dbUser.DisplayName,
			&dbUser.Avatar,
		)
		if err != nil {
			return nil, gqlerrors.HandleError(err)
		}

		dbUsers = append(dbUsers, dbUser)
	}

	if err := rows.Err(); err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	twitchUserIDs := make([]string, 0, len(dbUsers))
	twitchUserIndex := make(map[string]int, len(dbUsers))
	for i, user := range dbUsers {
		if user.Platform != platformentity.PlatformTwitch {
			continue
		}

		if user.Login != "" && user.DisplayName != "" && user.Avatar != "" {
			continue
		}

		if _, exists := twitchUserIndex[user.PlatformID]; exists {
			continue
		}

		twitchUserIndex[user.PlatformID] = i
		twitchUserIDs = append(twitchUserIDs, user.PlatformID)
	}

	if len(twitchUserIDs) > 0 {
		twitchUsers, err := data_loader.GetHelixUsersByIds(ctx, twitchUserIDs)
		if err != nil {
			return nil, gqlerrors.HandleError(err)
		}

		for i, userID := range twitchUserIDs {
			profile := twitchUsers[i]
			if profile == nil {
				continue
			}

			index := twitchUserIndex[userID]
			if dbUsers[index].Login == "" {
				dbUsers[index].Login = profile.Login
			}
			if dbUsers[index].DisplayName == "" {
				dbUsers[index].DisplayName = profile.DisplayName
			}
			if dbUsers[index].Avatar == "" {
				dbUsers[index].Avatar = profile.ProfileImageURL
			}
		}
	}

	countQuery, countArgs, err := countBuilder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("invalid count query on backend: %w", err)
	}

	var totalStats int64
	err = r.deps.Gorm.WithContext(ctx).Raw(countQuery, countArgs...).Scan(&totalStats).Error
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	mappedUsers := make([]gqlmodel.CommunityUser, 0, len(dbUsers))
	for _, user := range dbUsers {
		platform, err := mappers.EntityPlatformToGraphQL(user.Platform)
		if err != nil {
			return nil, gqlerrors.HandleError(err)
		}

		var avatar *string
		if user.Avatar != "" {
			avatar = &user.Avatar
		}

		mappedUsers = append(
			mappedUsers,
			gqlmodel.CommunityUser{
				ID:                user.PlatformID,
				Platform:          platform,
				PlatformID:        user.PlatformID,
				Login:             user.Login,
				DisplayName:       user.DisplayName,
				Avatar:            avatar,
				WatchedMs:         int(user.Watched),
				Messages:          int(user.Messages),
				UsedEmotes:        user.Emotes,
				UsedChannelPoints: int(user.UsedChannelPoints),
			},
		)
	}

	return &gqlmodel.CommunityUsersResponse{
		Users: mappedUsers,
		Total: int(totalStats),
	}, nil
}

// CommunityUser returns graph.CommunityUserResolver implementation.
func (r *Resolver) CommunityUser() graph.CommunityUserResolver { return &communityUserResolver{r} }

type communityUserResolver struct{ *Resolver }
