package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
)

// Donatello is the resolver for the donatello field.
func (r *queryResolver) Donatello(ctx context.Context) (*gqlmodel.DonatelloIntegration, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	id, err := r.deps.DonatelloIntegrationService.GetIDByChannelID(ctx, dashboardID)
	if err != nil {
		return nil, err
	}

	if id == nil {
		return nil, fmt.Errorf("donatello: internal error")
	}

	return &gqlmodel.DonatelloIntegration{
		IntegrationID: *id,
	}, nil
}
