package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	"github.com/twirapp/twir/apps/api-gql/internal/services/discord_integration"
)

// DiscordIntegrationConnectGuild is the resolver for the discordIntegrationConnectGuild field.
func (r *mutationResolver) DiscordIntegrationConnectGuild(ctx context.Context, code string) (
	bool,
	error,
) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.DiscordIntegrationService.ConnectGuild(ctx, dashboardID, code)
	if err != nil {
		return false, fmt.Errorf("cannot connect discord guild: %w", err)
	}

	return true, nil
}

// DiscordIntegrationDisconnectGuild is the resolver for the discordIntegrationDisconnectGuild field.
func (r *mutationResolver) DiscordIntegrationDisconnectGuild(
	ctx context.Context,
	guildID string,
) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.DiscordIntegrationService.DisconnectGuild(ctx, dashboardID, guildID)
	if err != nil {
		return false, fmt.Errorf("cannot disconnect discord guild: %w", err)
	}

	return true, nil
}

// DiscordIntegrationUpdateGuild is the resolver for the discordIntegrationUpdateGuild field.
func (r *mutationResolver) DiscordIntegrationUpdateGuild(
	ctx context.Context,
	guildID string,
	input gqlmodel.DiscordGuildUpdateInput,
) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	var (
		liveNotificationChannelsIds    *[]string
		additionalUsersIdsForLiveCheck *[]string
	)

	if input.LiveNotificationChannelsIds.IsSet() {
		v := input.LiveNotificationChannelsIds.Value()
		liveNotificationChannelsIds = &v
	}

	if input.AdditionalUsersIdsForLiveCheck.IsSet() {
		v := input.AdditionalUsersIdsForLiveCheck.Value()
		additionalUsersIdsForLiveCheck = &v
	}

	err = r.deps.DiscordIntegrationService.UpdateGuild(
		ctx,
		dashboardID,
		guildID,
		discord_integration.UpdateGuildInput{
			LiveNotificationEnabled:          input.LiveNotificationEnabled.Value(),
			LiveNotificationChannelsIds:      liveNotificationChannelsIds,
			LiveNotificationShowTitle:        input.LiveNotificationShowTitle.Value(),
			LiveNotificationShowCategory:     input.LiveNotificationShowCategory.Value(),
			LiveNotificationShowViewers:      input.LiveNotificationShowViewers.Value(),
			LiveNotificationMessage:          input.LiveNotificationMessage.Value(),
			LiveNotificationShowPreview:      input.LiveNotificationShowPreview.Value(),
			LiveNotificationShowProfileImage: input.LiveNotificationShowProfileImage.Value(),
			OfflineNotificationMessage:       input.OfflineNotificationMessage.Value(),
			ShouldDeleteMessageOnOffline:     input.ShouldDeleteMessageOnOffline.Value(),
			AdditionalUsersIdsForLiveCheck:   additionalUsersIdsForLiveCheck,
		},
	)
	if err != nil {
		return false, fmt.Errorf("cannot update discord guild: %w", err)
	}

	return true, nil
}

// DiscordIntegrationData is the resolver for the discordIntegrationData field.
func (r *queryResolver) DiscordIntegrationData(ctx context.Context) (
	*gqlmodel.DiscordIntegrationData,
	error,
) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	data, err := r.deps.DiscordIntegrationService.GetData(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("cannot get discord data: %w", err)
	}

	return mappers.MapDiscordIntegrationDataToGql(data), nil
}

// DiscordIntegrationAuthLink is the resolver for the discordIntegrationAuthLink field.
func (r *queryResolver) DiscordIntegrationAuthLink(ctx context.Context) (string, error) {
	return r.deps.DiscordIntegrationService.GetAuthLink(ctx)
}

// DiscordIntegrationGuildChannels is the resolver for the discordIntegrationGuildChannels field.
func (r *queryResolver) DiscordIntegrationGuildChannels(
	ctx context.Context,
	guildID string,
) ([]gqlmodel.DiscordGuildChannel, error) {
	channels, err := r.deps.DiscordIntegrationService.GetGuildChannels(ctx, guildID)
	if err != nil {
		return nil, fmt.Errorf("cannot get discord guild channels: %w", err)
	}

	return mappers.MapDiscordGuildChannelsToGql(channels), nil
}

// DiscordIntegrationGuildInfo is the resolver for the discordIntegrationGuildInfo field.
func (r *queryResolver) DiscordIntegrationGuildInfo(
	ctx context.Context,
	guildID string,
) (*gqlmodel.DiscordGuildInfo, error) {
	info, err := r.deps.DiscordIntegrationService.GetGuildInfo(ctx, guildID)
	if err != nil {
		return nil, fmt.Errorf("cannot get discord guild info: %w", err)
	}

	return mappers.MapDiscordGuildInfoToGql(info), nil
}
