package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlerrors"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	streamlabsintegration "github.com/twirapp/twir/apps/api-gql/internal/services/streamlabs_integration"
	integrationsmodel "github.com/twirapp/twir/libs/repositories/integrations/model"
)

// StreamlabsPostCode is the resolver for the streamlabsPostCode field.
func (r *mutationResolver) StreamlabsPostCode(ctx context.Context, input gqlmodel.IntegrationOAuthCodeInput) (bool, error) {
	sessions, ok := r.deps.Sessions.(integrationOAuthAttemptConsumer)
	if !ok {
		return false, gqlerrors.HandleError(fmt.Errorf("Streamlabs OAuth session support is not configured"))
	}
	if err := completeIntegrationOAuth(
		ctx,
		sessions,
		integrationsmodel.ServiceStreamLabs,
		input.Code,
		input.State,
		r.deps.StreamlabsIntegrationService.PostCode,
	); err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// StreamlabsLogout is the resolver for the streamlabsLogout field.
func (r *mutationResolver) StreamlabsLogout(ctx context.Context) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	err = r.deps.StreamlabsIntegrationService.Logout(ctx, dashboardID)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// Streamlabs is the resolver for the streamlabs field.
func (r *queryResolver) Streamlabs(ctx context.Context) (*gqlmodel.StreamlabsIntegration, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	entity, err := r.deps.StreamlabsIntegrationService.GetIntegrationData(ctx, dashboardID)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	return streamlabsintegration.MapEntityToGQLModel(entity), nil
}

// StreamlabsAuthLink is the resolver for the streamlabsAuthLink field.
func (r *queryResolver) StreamlabsAuthLink(ctx context.Context) (string, error) {
	sessions, ok := r.deps.Sessions.(integrationOAuthAttemptCreator)
	if !ok {
		return "", gqlerrors.HandleError(fmt.Errorf("Streamlabs OAuth session support is not configured"))
	}
	authLink, err := createIntegrationOAuthLink(
		ctx,
		sessions,
		integrationsmodel.ServiceStreamLabs,
		func(ctx context.Context, state string) (string, error) {
			response, err := r.deps.StreamlabsIntegrationService.GetAuthLink(ctx, state)
			if err != nil {
				return "", err
			}
			return response.Link, nil
		},
	)
	if err != nil {
		return "", gqlerrors.HandleError(err)
	}

	return authLink, nil
}
