package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
)

// LastfmPostCode is the resolver for the lastfmPostCode field.
func (r *mutationResolver) LastfmPostCode(ctx context.Context, code string) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.LastfmIntegrationService.PostCode(ctx, dashboardID, code)
	if err != nil {
		return false, fmt.Errorf("cannot post lastfm code: %w", err)
	}

	return true, nil
}

// LastfmLogout is the resolver for the lastfmLogout field.
func (r *mutationResolver) LastfmLogout(ctx context.Context) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.LastfmIntegrationService.Logout(ctx, dashboardID)
	if err != nil {
		return false, fmt.Errorf("cannot logout from lastfm: %w", err)
	}

	return true, nil
}

// LastfmData is the resolver for the lastfmData field.
func (r *queryResolver) LastfmData(ctx context.Context) (*gqlmodel.LastfmIntegration, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	data, err := r.deps.LastfmIntegrationService.GetData(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("cannot get lastfm data: %w", err)
	}

	return mappers.MapLastfmIntegrationDataToGql(data), nil
}

// LastfmAuthLink is the resolver for the lastfmAuthLink field.
func (r *queryResolver) LastfmAuthLink(ctx context.Context) (string, error) {
	return r.deps.LastfmIntegrationService.GetAuthLink(ctx)
}
