package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
)

// ValorantPostCode is the resolver for the valorantPostCode field.
func (r *mutationResolver) ValorantPostCode(ctx context.Context, code string) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.ValorantIntegrationService.PostCode(ctx, dashboardID, code)
	if err != nil {
		return false, fmt.Errorf("cannot post valorant code: %w", err)
	}

	return true, nil
}

// ValorantLogout is the resolver for the valorantLogout field.
func (r *mutationResolver) ValorantLogout(ctx context.Context) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.ValorantIntegrationService.Logout(ctx, dashboardID)
	if err != nil {
		return false, fmt.Errorf("cannot logout from valorant: %w", err)
	}

	return true, nil
}

// ValorantData is the resolver for the valorantData field.
func (r *queryResolver) ValorantData(ctx context.Context) (*gqlmodel.ValorantIntegration, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	data, err := r.deps.ValorantIntegrationService.GetData(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("cannot get valorant data: %w", err)
	}

	return mappers.MapValorantIntegrationDataToGql(data), nil
}

// ValorantAuthLink is the resolver for the valorantAuthLink field.
func (r *queryResolver) ValorantAuthLink(ctx context.Context) (string, error) {
	return r.deps.ValorantIntegrationService.GetAuthLink(ctx)
}
