package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	vkintegration "github.com/twirapp/twir/apps/api-gql/internal/services/vk_integration"
)

// VkPostCode is the resolver for the vkPostCode field.
func (r *mutationResolver) VkPostCode(ctx context.Context, code string) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.VKIntegrationService.PostCode(ctx, dashboardID, code)
	if err != nil {
		return false, err
	}

	return true, nil
}

// VkLogout is the resolver for the vkLogout field.
func (r *mutationResolver) VkLogout(ctx context.Context) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.VKIntegrationService.Logout(ctx, dashboardID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// Vk is the resolver for the vk field.
func (r *queryResolver) Vk(ctx context.Context) (*gqlmodel.VKIntegration, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	entity, err := r.deps.VKIntegrationService.GetIntegrationData(ctx, dashboardID)
	if err != nil {
		return nil, err
	}

	return vkintegration.MapEntityToGQLModel(entity), nil
}

// VkAuthLink is the resolver for the vkAuthLink field.
func (r *queryResolver) VkAuthLink(ctx context.Context) (string, error) {
	authLink, err := r.deps.VKIntegrationService.GetAuthLink(ctx)
	if err != nil {
		return "", err
	}

	return authLink.Link, nil
}
