package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	"github.com/twirapp/twir/apps/api-gql/internal/services/webhook_notifications"
	channelsmoduleswebhooks "github.com/twirapp/twir/libs/repositories/channels_modules_webhooks"
)

// WebhookNotificationsCreate is the resolver for the webhookNotificationsCreate field.
func (r *mutationResolver) WebhookNotificationsCreate(ctx context.Context, input gqlmodel.WebhookNotificationsCreateInput) (*gqlmodel.WebhookNotificationsSettings, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return nil, err
	}

	settings, err := r.deps.WebhookNotificationsService.Create(
		ctx,
		webhook_notifications.CreateInput{
			ChannelID:                 dashboardID,
			ActorID:                   user.ID,
			Enabled:                   input.Enabled,
			GithubIssuesEnabled:       input.GithubIssues,
			GithubPullRequestsEnabled: input.GithubPullRequests,
			GithubCommitsEnabled:      input.GithubCommits,
		},
	)
	if err != nil {
		return nil, err
	}

	result := mappers.WebhookNotificationsEntityToGql(settings)
	return &result, nil
}

// WebhookNotificationsUpdate is the resolver for the webhookNotificationsUpdate field.
func (r *mutationResolver) WebhookNotificationsUpdate(ctx context.Context, id string, input gqlmodel.WebhookNotificationsUpdateInput) (*gqlmodel.WebhookNotificationsSettings, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return nil, err
	}

	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	settings, err := r.deps.WebhookNotificationsService.Update(
		ctx,
		parsedID,
		webhook_notifications.UpdateInput{
			ChannelID:                 dashboardID,
			ActorID:                   user.ID,
			Enabled:                   input.Enabled.Value(),
			GithubIssuesEnabled:       input.GithubIssues.Value(),
			GithubPullRequestsEnabled: input.GithubPullRequests.Value(),
			GithubCommitsEnabled:      input.GithubCommits.Value(),
		},
	)
	if err != nil {
		return nil, err
	}

	result := mappers.WebhookNotificationsEntityToGql(settings)
	return &result, nil
}

// WebhookNotificationsDelete is the resolver for the webhookNotificationsDelete field.
func (r *mutationResolver) WebhookNotificationsDelete(ctx context.Context, id string) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return false, err
	}

	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}

	if err := r.deps.WebhookNotificationsService.Delete(
		ctx,
		webhook_notifications.DeleteInput{
			ID:        parsedID,
			ChannelID: dashboardID,
			ActorID:   user.ID,
		},
	); err != nil {
		return false, err
	}

	return true, nil
}

// WebhookNotifications is the resolver for the webhookNotifications field.
func (r *queryResolver) WebhookNotifications(ctx context.Context) (*gqlmodel.WebhookNotificationsSettings, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	settings, err := r.deps.WebhookNotificationsService.GetByChannelID(ctx, dashboardID)
	if err != nil {
		if errors.Is(err, channelsmoduleswebhooks.ErrSettingsNotFound) {
			return nil, nil
		}
		return nil, err
	}

	result := mappers.WebhookNotificationsEntityToGql(settings)
	return &result, nil
}
