package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	"github.com/twirapp/twir/apps/api-gql/internal/services/obs_websocket_module"
)

// ObsWebsocketUpdate is the resolver for the obsWebsocketUpdate field.
func (r *mutationResolver) ObsWebsocketUpdate(ctx context.Context, input gqlmodel.ObsWebsocketUpdateInput) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	err = r.deps.ObsWebsocketModuleService.UpdateObsWebsocket(
		ctx,
		dashboardID,
		input.ServerPort,
		input.ServerAddress,
		input.ServerPassword,
	)
	if err != nil {
		return false, fmt.Errorf("cannot update obs websocket: %w", err)
	}

	return true, nil
}

// ObsWebsocketUpdateFromOverlay is the resolver for the obsWebsocketUpdateFromOverlay field.
func (r *mutationResolver) ObsWebsocketUpdateFromOverlay(ctx context.Context, apiKey string, input gqlmodel.ObsWebsocketOverlayInput) (bool, error) {
	err := r.deps.ObsWebsocketModuleService.UpdateFromOverlay(
		ctx,
		apiKey,
		obs_websocket_module.UpdateFromOverlayInput{
			Scenes:       input.Scenes,
			Sources:      input.Sources,
			AudioSources: input.AudioSources,
		},
	)
	if err != nil {
		return false, fmt.Errorf("cannot update obs websocket from overlay: %w", err)
	}

	return true, nil
}

// ObsWebsocketData is the resolver for the obsWebsocketData field.
func (r *queryResolver) ObsWebsocketData(ctx context.Context) (*gqlmodel.ObsWebsocketModule, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	data, err := r.deps.ObsWebsocketModuleService.GetObsWebsocketData(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("cannot get obs websocket data: %w", err)
	}

	return mappers.MapObsWebsocketModuleDataToGql(data), nil
}

// ObsWebsocketData is the resolver for the obsWebsocketData field.
func (r *subscriptionResolver) ObsWebsocketData(ctx context.Context, apiKey string) (<-chan *gqlmodel.ObsWebsocketModule, error) {
	settingsChan, err := r.deps.ObsWebsocketModuleService.SettingsSubscriptionSignalerByApiKey(
		ctx,
		apiKey,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to obs websocket settings: %w", err)
	}

	outputChan := make(chan *gqlmodel.ObsWebsocketModule, 1)

	go func() {
		defer close(outputChan)

		for {
			select {
			case <-ctx.Done():
				return
			case data, ok := <-settingsChan:
				if !ok {
					return
				}

				outputChan <- mappers.MapObsWebsocketModuleDataToGql(&data)
			}
		}
	}()

	return outputChan, nil
}

// ObsWebsocketCommands is the resolver for the obsWebsocketCommands field.
func (r *subscriptionResolver) ObsWebsocketCommands(ctx context.Context, apiKey string) (<-chan *gqlmodel.ObsWebsocketCommand, error) {
	commandsChan, err := r.deps.ObsWebsocketModuleService.CommandsSubscriptionByApiKey(
		ctx,
		apiKey,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to obs websocket commands: %w", err)
	}

	outputChan := make(chan *gqlmodel.ObsWebsocketCommand, 1)

	go func() {
		defer close(outputChan)

		for {
			select {
			case <-ctx.Done():
				return
			case cmd, ok := <-commandsChan:
				if !ok {
					return
				}

				outputChan <- mappers.MapObsWebsocketCommandToGql(&cmd)
			}
		}
	}()

	return outputChan, nil
}
