package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlerrors"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/graph"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	"github.com/twirapp/twir/apps/api-gql/internal/services/dota"
)

// SteamProfile is the resolver for the steamProfile field.
func (r *dotaSettingsResolver) SteamProfile(ctx context.Context, obj *gqlmodel.DotaSettings) (*gqlmodel.DotaSteamProfile, error) {
	if obj.SteamAccountID == nil || *obj.SteamAccountID == "" {
		return nil, nil
	}

	profile, err := r.deps.DotaService.SteamProfile(ctx, *obj.SteamAccountID)
	if err != nil {
		return nil, fmt.Errorf("failed to get steam profile: %w", err)
	}
	if profile == nil {
		return nil, nil
	}

	return &gqlmodel.DotaSteamProfile{
		Name:       profile.PersonaName,
		Avatar:     profile.AvatarFull,
		ProfileURL: profile.ProfileURL,
	}, nil
}

// GsiConfig is the resolver for the gsiConfig field.
func (r *dotaSettingsResolver) GsiConfig(ctx context.Context, obj *gqlmodel.DotaSettings) (string, error) {
	settings, err := getDotaSettings(ctx, &r.deps)
	if err != nil {
		return "", err
	}

	return r.deps.DotaService.GsiConfig(settings), nil
}

// DotaUpdate is the resolver for the dotaUpdate field.
func (r *mutationResolver) DotaUpdate(ctx context.Context, input gqlmodel.DotaUpdateInput) (*gqlmodel.DotaSettings, error) {
	dashboardID, err := getDotaDashboardID(ctx, r.deps.Sessions)
	if err != nil {
		return nil, err
	}

	mapped := mappers.MapDotaUpdateInputToEntity(input)
	updated, err := r.deps.DotaService.Update(
		ctx,
		dashboardID,
		dota.UpdateInput{
			Enabled:            mapped.Enabled,
			Mmr:                mapped.Mmr,
			MmrDelta:           mapped.MmrDelta,
			PredictionSettings: mapped.PredictionSettings,
			ChatEvents:         mapped.ChatEvents,
			CommandsSettings:   mapped.CommandsSettings,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("failed to update dota settings: %w", err)
	}

	converted := mappers.MapDotaEntityToGQL(updated)
	return &converted, nil
}

// DotaSteamLink is the resolver for the dotaSteamLink field.
func (r *mutationResolver) DotaSteamLink(ctx context.Context, queryString string) (*gqlmodel.DotaSettings, error) {
	dashboardID, err := getDotaDashboardID(ctx, r.deps.Sessions)
	if err != nil {
		return nil, err
	}

	updated, err := r.deps.DotaService.SteamLink(ctx, dashboardID, queryString)
	if err != nil {
		return nil, fmt.Errorf("failed to link steam account: %w", err)
	}

	converted := mappers.MapDotaEntityToGQL(updated)
	return &converted, nil
}

// DotaSteamUnlink is the resolver for the dotaSteamUnlink field.
func (r *mutationResolver) DotaSteamUnlink(ctx context.Context) (*gqlmodel.DotaSettings, error) {
	dashboardID, err := getDotaDashboardID(ctx, r.deps.Sessions)
	if err != nil {
		return nil, err
	}

	updated, err := r.deps.DotaService.SteamUnlink(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("failed to unlink steam account: %w", err)
	}

	converted := mappers.MapDotaEntityToGQL(updated)
	return &converted, nil
}

// DotaResetSession is the resolver for the dotaResetSession field.
func (r *mutationResolver) DotaResetSession(ctx context.Context) (*gqlmodel.DotaSettings, error) {
	dashboardID, err := getDotaDashboardID(ctx, r.deps.Sessions)
	if err != nil {
		return nil, err
	}

	updated, err := r.deps.DotaService.ResetSession(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("failed to reset dota session: %w", err)
	}

	converted := mappers.MapDotaEntityToGQL(updated)
	return &converted, nil
}

// DotaRegenerateGsiToken is the resolver for the dotaRegenerateGsiToken field.
func (r *mutationResolver) DotaRegenerateGsiToken(ctx context.Context) (*gqlmodel.DotaSettings, error) {
	dashboardID, err := getDotaDashboardID(ctx, r.deps.Sessions)
	if err != nil {
		return nil, err
	}

	updated, err := r.deps.DotaService.RegenerateGsiToken(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("failed to regenerate dota gsi token: %w", err)
	}

	converted := mappers.MapDotaEntityToGQL(updated)
	return &converted, nil
}

// Dota is the resolver for the dota field.
func (r *queryResolver) Dota(ctx context.Context) (*gqlmodel.DotaSettings, error) {
	settings, err := getDotaSettings(ctx, &r.deps)
	if err != nil {
		return nil, err
	}

	converted := mappers.MapDotaEntityToGQL(settings)
	return &converted, nil
}

// DotaSteamAuthLink is the resolver for the dotaSteamAuthLink field.
func (r *queryResolver) DotaSteamAuthLink(ctx context.Context) (string, error) {
	link, err := r.deps.DotaService.SteamAuthLink()
	if err != nil {
		return "", fmt.Errorf("failed to build steam auth link: %w", err)
	}

	return link, nil
}

// DotaState is the resolver for the dotaState field.
func (r *subscriptionResolver) DotaState(ctx context.Context, apiKey string) (<-chan *gqlmodel.DotaState, error) {
	updateChan, err := r.deps.DotaService.StateSubscriptionByApiKey(ctx, apiKey)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	outputChan := make(chan *gqlmodel.DotaState, 1)
	go func() {
		defer close(outputChan)
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-updateChan:
				if !ok {
					return
				}

				converted := &gqlmodel.DotaState{
					ChannelID:      msg.ChannelID,
					InGame:         msg.InGame,
					Mmr:            msg.Mmr,
					SessionWins:    msg.SessionWins,
					SessionLosses:  msg.SessionLosses,
					WinProbability: msg.WinProbability,
					HeroName:       msg.HeroName,
					MatchID:        fmt.Sprintf("%d", msg.MatchID),
					TeamIsRadiant:  msg.TeamIsRadiant,
					TeamKnown:      msg.TeamKnown,
				}
				select {
				case outputChan <- converted:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return outputChan, nil
}

// DotaSettings returns graph.DotaSettingsResolver implementation.
func (r *Resolver) DotaSettings() graph.DotaSettingsResolver { return &dotaSettingsResolver{r} }

type dotaSettingsResolver struct{ *Resolver }
