package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/json"

	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlerrors"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/scalars"
)

// StorageSet is the resolver for the storageSet field.
func (r *mutationResolver) StorageSet(ctx context.Context, key string, value scalars.JSON) (*gqlmodel.StorageEntry, error) {
	dashboardId, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	entry, err := r.deps.ChannelsStorageService.Set(ctx, dashboardId, key, json.RawMessage(value))
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	converted := mappers.StorageEntryModelToGql(entry)
	return &converted, nil
}

// StorageDelete is the resolver for the storageDelete field.
func (r *mutationResolver) StorageDelete(ctx context.Context, key string) (bool, error) {
	dashboardId, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	if err := r.deps.ChannelsStorageService.Delete(ctx, dashboardId, key); err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// StorageDeleteAll is the resolver for the storageDeleteAll field.
func (r *mutationResolver) StorageDeleteAll(ctx context.Context) (bool, error) {
	dashboardId, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, err
	}

	if err := r.deps.ChannelsStorageService.DeleteAllByChannelID(ctx, dashboardId); err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// Storage is the resolver for the storage field.
func (r *queryResolver) Storage(ctx context.Context) (*gqlmodel.StorageData, error) {
	dashboardId, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, err
	}

	entries, err := r.deps.ChannelsStorageService.GetAllByChannelID(ctx, dashboardId)
	if err != nil {
		return nil, err
	}

	totalSize, err := r.deps.ChannelsStorageService.GetTotalSizeByChannelID(ctx, dashboardId)
	if err != nil {
		return nil, err
	}

	result := make([]gqlmodel.StorageEntry, 0, len(entries))
	for _, entry := range entries {
		result = append(result, mappers.StorageEntryModelToGql(entry))
	}

	return &gqlmodel.StorageData{
		Entries:   result,
		TotalSize: int(totalSize),
	}, nil
}
