package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/url"

	"github.com/google/uuid"
	"github.com/guregu/null"
	helix "github.com/nicklaw5/helix/v2"
	"github.com/samber/lo"
	data_loader "github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/dataloader"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlerrors"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/graph"
	"github.com/twirapp/twir/apps/api-gql/internal/server/gincontext"
	"github.com/twirapp/twir/apps/api-gql/internal/services/users"
	platformentity "github.com/twirapp/twir/libs/entities/platform"
	model "github.com/twirapp/twir/libs/gomodels"
	userplatformaccountsrepository "github.com/twirapp/twir/libs/repositories/user_platform_accounts"
	"gorm.io/gorm"
)

// TwitchProfile is the resolver for the twitchProfile field.
func (r *authenticatedUserResolver) TwitchProfile(ctx context.Context, obj *gqlmodel.AuthenticatedUser) (*gqlmodel.TwirUserTwitchInfo, error) {
	userID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	account, err := r.deps.UserPlatformAccountsRepository.GetByUserIDAndPlatform(
		ctx,
		userID,
		platformentity.PlatformTwitch,
	)
	if err != nil {
		if errors.Is(err, userplatformaccountsrepository.ErrNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("get twitch platform account: %w", err)
	}

	return data_loader.GetHelixUserById(ctx, account.PlatformUserID)
}

// AvailableDashboards is the resolver for the availableDashboards field.
func (r *authenticatedUserResolver) AvailableDashboards(ctx context.Context, obj *gqlmodel.AuthenticatedUser) ([]gqlmodel.Dashboard, error) {
	return r.getAvailableDashboards(ctx, obj)
}

// KickProfile is the resolver for the kickProfile field.
func (r *authenticatedUserResolver) KickProfile(ctx context.Context, obj *gqlmodel.AuthenticatedUser) (*gqlmodel.KickProfile, error) {
	kickUser, err := r.deps.Sessions.GetSessionKickUser(ctx)
	if err != nil {
		return nil, nil
	}

	var profilePicture *string
	if kickUser.Avatar != "" {
		profilePicture = &kickUser.Avatar
	}

	return &gqlmodel.KickProfile{
		ID:             kickUser.ID,
		Slug:           kickUser.Login,
		DisplayName:    kickUser.Login,
		ProfilePicture: profilePicture,
		IsLive:         false,
		FollowersCount: 0,
	}, nil
}

// LinkedAccounts is the resolver for the linkedAccounts field.
func (r *authenticatedUserResolver) LinkedAccounts(ctx context.Context, obj *gqlmodel.AuthenticatedUser) ([]gqlmodel.LinkedAccount, error) {
	userID, err := r.deps.Sessions.GetInternalUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("not authenticated: %w", err)
	}

	accounts, err := r.deps.UserPlatformAccountsRepository.GetAllByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get linked accounts: %w", err)
	}

	result := make([]gqlmodel.LinkedAccount, len(accounts))
	for i, acc := range accounts {
		avatar := acc.PlatformAvatar
		result[i] = gqlmodel.LinkedAccount{
			Platform:       string(acc.Platform),
			PlatformUserID: acc.PlatformUserID,
			PlatformLogin:  acc.PlatformLogin,
			PlatformAvatar: &avatar,
		}
	}
	return result, nil
}

// CurrentPlatform is the resolver for the currentPlatform field.
func (r *authenticatedUserResolver) CurrentPlatform(ctx context.Context, obj *gqlmodel.AuthenticatedUser) (string, error) {
	return r.deps.Sessions.GetCurrentPlatform(ctx)
}

// TwitchProfile is the resolver for the twitchProfile field.
func (r *channelUserInfoResolver) TwitchProfile(ctx context.Context, obj *gqlmodel.ChannelUserInfo) (*gqlmodel.TwirUserTwitchInfo, error) {
	return data_loader.GetHelixUserById(ctx, obj.UserID)
}

// TwitchProfile is the resolver for the twitchProfile field.
func (r *dashboardResolver) TwitchProfile(ctx context.Context, obj *gqlmodel.Dashboard) (*gqlmodel.TwirUserTwitchInfo, error) {
	channel, err := r.deps.ChannelsRepository.GetByID(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("get channel: %w", err)
	}
	if channel.IsNil() {
		return nil, nil
	}

	account, err := r.deps.UserPlatformAccountsRepository.GetByUserIDAndPlatform(
		ctx,
		channel.UserID,
		platformentity.PlatformTwitch,
	)
	if err != nil {
		if errors.Is(err, userplatformaccountsrepository.ErrNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("get twitch platform account: %w", err)
	}

	return data_loader.GetHelixUserById(ctx, account.PlatformUserID)
}

// Plan is the resolver for the plan field.
func (r *dashboardResolver) Plan(ctx context.Context, obj *gqlmodel.Dashboard) (*gqlmodel.Plan, error) {
	// Use dataloader to get plan by channel ID
	return data_loader.GetPlanByChannelID(ctx, data_loader.GetPlayByChannelId{
		ChannelID: obj.ID,
		PlanID:    obj.PlanID,
	})
}

// AuthenticatedUserSelectDashboard is the resolver for the authenticatedUserSelectDashboard field.
func (r *mutationResolver) AuthenticatedUserSelectDashboard(ctx context.Context, dashboardID string) (bool, error) {
	if err := r.deps.Sessions.SetSessionSelectedDashboard(ctx, dashboardID); err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// AuthenticatedUserUpdateSettings is the resolver for the authenticatedUserUpdateSettings field.
func (r *mutationResolver) AuthenticatedUserUpdateSettings(ctx context.Context, opts gqlmodel.UserUpdateSettingsInput) (bool, error) {
	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	entity := &model.Users{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where("id = ?", user.ID).
		First(entity).Error; err != nil {
		return false, fmt.Errorf("failed to get user: %w", err)
	}

	if opts.HideOnLandingPage.IsSet() {
		entity.HideOnLandingPage = *opts.HideOnLandingPage.Value()
	}

	if err := r.deps.Gorm.
		WithContext(ctx).
		Save(entity).Error; err != nil {
		return false, fmt.Errorf("failed to save user: %w", err)
	}

	return true, nil
}

// AuthenticatedUserRegenerateAPIKey is the resolver for the authenticatedUserRegenerateApiKey field.
func (r *mutationResolver) AuthenticatedUserRegenerateAPIKey(ctx context.Context) (string, error) {
	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return "", gqlerrors.HandleError(err)
	}

	entity := &model.Users{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where("id = ?", user.ID).
		First(entity).Error; err != nil {
		return "", fmt.Errorf("failed to get user: %w", err)
	}

	entity.ApiKey = uuid.NewString()

	if err := r.deps.Gorm.
		WithContext(ctx).
		Save(entity).Error; err != nil {
		return "", fmt.Errorf("failed to save user: %w", err)
	}

	return entity.ApiKey, nil
}

// AuthenticatedUserUpdatePublicPage is the resolver for the authenticatedUserUpdatePublicPage field.
func (r *mutationResolver) AuthenticatedUserUpdatePublicPage(ctx context.Context, opts gqlmodel.UserUpdatePublicSettingsInput) (bool, error) {
	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	currentSettings := &model.ChannelPublicSettings{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where(
			"channel_id = ?",
			user.ID,
		).
		Preload("SocialLinks").
		// init default settings
		FirstOrInit(
			currentSettings,
			&model.ChannelPublicSettings{
				ChannelID: user.ID,
			},
		).
		Error; err != nil {
		return false, fmt.Errorf("failed to get public settings: %w", err)
	}

	txErr := r.deps.Gorm.WithContext(ctx).Transaction(
		func(tx *gorm.DB) error {
			if opts.Description.IsSet() {
				currentSettings.Description = null.StringFromPtr(opts.Description.Value())
			}

			if opts.SocialLinks.IsSet() {
				if err := tx.
					Where("settings_id = ?", currentSettings.ID).
					Delete(&model.ChannelPublicSettingsSocialLink{}).
					Error; err != nil {
					return gqlerrors.HandleError(err)
				}

				links := make([]model.ChannelPublicSettingsSocialLink, 0, len(opts.SocialLinks.Value()))
				for _, link := range opts.SocialLinks.Value() {
					links = append(
						links,
						model.ChannelPublicSettingsSocialLink{
							ID:         uuid.New(),
							SettingsID: currentSettings.ID,
							Title:      link.Title,
							Href:       link.Href,
						},
					)
				}

				currentSettings.SocialLinks = links
			}

			return tx.Save(currentSettings).Error
		},
	)

	if txErr != nil {
		return false, fmt.Errorf("failed to update public settings: %w", txErr)
	}

	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	if err := r.deps.Sessions.SessionLogout(ctx); err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// UnlinkPlatformAccount is the resolver for the unlinkPlatformAccount field.
func (r *mutationResolver) UnlinkPlatformAccount(ctx context.Context, platform string) (bool, error) {
	userID, err := r.deps.Sessions.GetInternalUserID(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	accounts, err := r.deps.UserPlatformAccountsRepository.GetAllByUserID(ctx, userID)
	if err != nil {
		return false, fmt.Errorf("failed to get platform accounts: %w", err)
	}

	if len(accounts) <= 1 {
		return false, fmt.Errorf("cannot unlink the only remaining platform account")
	}

	targetPlatform := platformentity.Platform(platform)
	var accountID *uuid.UUID
	for _, acc := range accounts {
		if acc.Platform == targetPlatform {
			id := acc.ID
			accountID = &id
			break
		}
	}

	if accountID == nil {
		return false, fmt.Errorf("platform account not found")
	}

	if err := r.deps.UserPlatformAccountsRepository.Delete(ctx, *accountID); err != nil {
		return false, fmt.Errorf("failed to delete platform account: %w", err)
	}

	return true, nil
}

// AuthenticatedUser is the resolver for the authenticatedUser field.
func (r *queryResolver) AuthenticatedUser(ctx context.Context) (*gqlmodel.AuthenticatedUser, error) {
	sessionUser, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return nil, fmt.Errorf("not authenticated: %w", err)
	}

	dashboardId, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	user := model.Users{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where("id = ?", sessionUser.ID).
		Preload("Channel").
		First(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	authedUser := &gqlmodel.AuthenticatedUser{
		ID:                  user.ID,
		IsBotAdmin:          user.IsBotAdmin,
		IsBanned:            user.IsBanned,
		HideOnLandingPage:   user.HideOnLandingPage,
		APIKey:              user.ApiKey,
		SelectedDashboardID: dashboardId,
	}

	if user.Channel != nil {
		authedUser.IsEnabled = &user.Channel.IsEnabled
		authedUser.IsBotModerator = &user.Channel.IsBotMod
		authedUser.BotID = &user.Channel.BotID
		authedUser.PlanID = user.Channel.PlanID
	}

	return authedUser, nil
}

// UserPublicSettings is the resolver for the userPublicSettings field.
func (r *queryResolver) UserPublicSettings(ctx context.Context, userID *string) (*gqlmodel.PublicSettings, error) {
	dashboardId, _ := r.deps.Sessions.GetSelectedDashboard(ctx)

	var idForFetch string
	if userID != nil {
		idForFetch = *userID
	} else if dashboardId != "" {
		idForFetch = dashboardId
	}

	if idForFetch == "" {
		return nil, fmt.Errorf("id for fetch not setted in request or session")
	}

	entity := &model.ChannelPublicSettings{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where(
			"channel_id = ?",
			idForFetch,
		).
		Preload("SocialLinks").
		Find(entity).Error; err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	settings := &gqlmodel.PublicSettings{
		Description: entity.Description.Ptr(),
		SocialLinks: lo.Map(
			entity.SocialLinks,
			func(item model.ChannelPublicSettingsSocialLink, _ int) gqlmodel.SocialLink {
				return gqlmodel.SocialLink{
					Title: item.Title,
					Href:  item.Href,
				}
			},
		),
	}

	return settings, nil
}

// AuthLink is the resolver for the authLink field.
func (r *queryResolver) AuthLink(ctx context.Context, redirectTo string) (string, error) {
	baseUrl, err := gincontext.GetBaseUrlFromContext(ctx, r.deps.Config.SiteBaseUrl)
	if err != nil {
		return "", gqlerrors.HandleError(err)
	}

	if redirectTo == "" {
		return "", fmt.Errorf("incorrect auth link %s", redirectTo)
	}

	u, err := url.Parse(baseUrl)
	if err != nil {
		return "", fmt.Errorf("failed to parse base url: %w", err)
	}

	twitchClient, err := helix.NewClientWithContext(
		ctx, &helix.Options{
			ClientID:    r.deps.Config.TwitchClientId,
			RedirectURI: u.JoinPath("login").String(),
		},
	)
	if err != nil {
		return "", fmt.Errorf("failed to create twitch client: %w", err)
	}

	state := base64.StdEncoding.EncodeToString([]byte(redirectTo))

	if r.deps.Config.TwitchMockEnabled {
		siteURL, err := url.Parse(r.deps.Config.SiteBaseUrl)
		if err != nil {
			return "", fmt.Errorf("failed to parse site base url: %w", err)
		}
		mockAuthUrl := fmt.Sprintf(
			"%s/oauth2/authorize?response_type=code&client_id=%s&redirect_uri=%s&scope=&state=%s",
			r.deps.Config.TwitchMockAuthUrl,
			r.deps.Config.TwitchClientId,
			url.QueryEscape(siteURL.JoinPath("login").String()),
			url.QueryEscape(state),
		)
		return mockAuthUrl, nil
	}

	twitchScopes := []string{
		"moderation:read",
		"channel:manage:broadcast",
		"channel:read:redemptions",
		"channel:manage:redemptions",
		"moderator:read:chatters",
		"moderator:manage:shoutouts",
		"moderator:manage:banned_users",
		"channel:read:vips",
		"channel:manage:vips",
		"channel:manage:moderators",
		"moderator:read:followers",
		"moderator:manage:chat_settings",
		"channel:read:polls",
		"channel:manage:polls",
		"channel:read:predictions",
		"channel:manage:predictions",
		"channel:read:subscriptions",
		"channel:moderate",
		"user:read:follows",
		"channel:bot",
		"channel:manage:raids",
	}

	url := twitchClient.GetAuthorizationURL(
		&helix.AuthorizationURLParams{
			ResponseType: "code",
			Scopes:       twitchScopes,
			State:        state,
			ForceVerify:  false,
		},
	)

	return url, nil
}

// ChannelUserInfo is the resolver for the channelUserInfo field.
func (r *queryResolver) ChannelUserInfo(ctx context.Context, userID string) (*gqlmodel.ChannelUserInfo, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	info, err := r.deps.UsersService.GetChannelUserInfo(
		ctx, users.ChannelUserInfoInput{
			ChannelID: dashboardID,
			UserID:    userID,
		},
	)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	return &gqlmodel.ChannelUserInfo{
		UserID:            info.ID,
		TwitchProfile:     nil,
		IsMod:             info.IsMod,
		IsVip:             info.IsVip,
		IsSubscriber:      info.IsSubscriber,
		WatchedMs:         info.Watched,
		Messages:          info.Messages,
		UsedEmotes:        info.UsedEmotes,
		UsedChannelPoints: info.UsedChannelPoints,
		FollowerSince:     info.FollowerSince,
	}, nil
}

// AuthenticatedUser returns graph.AuthenticatedUserResolver implementation.
func (r *Resolver) AuthenticatedUser() graph.AuthenticatedUserResolver {
	return &authenticatedUserResolver{r}
}

// ChannelUserInfo returns graph.ChannelUserInfoResolver implementation.
func (r *Resolver) ChannelUserInfo() graph.ChannelUserInfoResolver {
	return &channelUserInfoResolver{r}
}

// Dashboard returns graph.DashboardResolver implementation.
func (r *Resolver) Dashboard() graph.DashboardResolver { return &dashboardResolver{r} }

type authenticatedUserResolver struct{ *Resolver }
type channelUserInfoResolver struct{ *Resolver }
type dashboardResolver struct{ *Resolver }
