package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/guregu/null"
	"github.com/samber/lo"
	data_loader "github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/dataloader"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlerrors"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/gqlmodel"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/graph"
	"github.com/twirapp/twir/apps/api-gql/internal/delivery/gql/mappers"
	"github.com/twirapp/twir/apps/api-gql/internal/services/users"
	platformentity "github.com/twirapp/twir/libs/entities/platform"
	model "github.com/twirapp/twir/libs/gomodels"
	channelsrepository "github.com/twirapp/twir/libs/repositories/channels"
	usersmodel "github.com/twirapp/twir/libs/repositories/users/model"
	"gorm.io/gorm"
)

// AvailableDashboards is the resolver for the availableDashboards field.
func (r *authenticatedUserResolver) AvailableDashboards(ctx context.Context, obj *gqlmodel.AuthenticatedUser) ([]gqlmodel.Dashboard, error) {
	return r.getAvailableDashboards(ctx, obj)
}

// LinkedAccounts is the resolver for the linkedAccounts field.
func (r *authenticatedUserResolver) LinkedAccounts(ctx context.Context, obj *gqlmodel.AuthenticatedUser) ([]gqlmodel.LinkedAccount, error) {
	channel, err := r.getAuthenticatedUserChannel(ctx)
	if err != nil {
		return nil, fmt.Errorf("get authenticated user channel: %w", err)
	}
	return r.linkedAccountsForChannel(ctx, channel)
}

// CurrentPlatform is the resolver for the currentPlatform field.
func (r *authenticatedUserResolver) CurrentPlatform(ctx context.Context, obj *gqlmodel.AuthenticatedUser) (string, error) {
	return r.deps.Sessions.GetCurrentPlatform(ctx)
}

// TwitchProfile is the resolver for the twitchProfile field.
func (r *channelUserInfoResolver) TwitchProfile(ctx context.Context, obj *gqlmodel.ChannelUserInfo) (*gqlmodel.TwirUserTwitchInfo, error) {
	parsedUserID, err := uuid.Parse(obj.UserID)
	if err != nil {
		return nil, nil
	}

	user, err := r.deps.UsersRepository.GetByID(ctx, parsedUserID)
	if err != nil {
		if err == usersmodel.ErrNotFound {
			return nil, nil
		}
		return nil, fmt.Errorf("get user: %w", err)
	}

	return data_loader.GetHelixUserById(ctx, user.PlatformID)
}

// Profile is the resolver for the profile field.
func (r *dashboardResolver) Profile(ctx context.Context, obj *gqlmodel.Dashboard) (*gqlmodel.LinkedAccount, error) {
	channelID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid channel id: %w", err)
	}

	channel, err := r.deps.ChannelService.GetChannelByID(ctx, channelID)
	if err != nil {
		return nil, fmt.Errorf("get channel: %w", err)
	}
	if channel.IsNil() || len(channel.Bindings) == 0 {
		return nil, nil
	}

	selected := channel.Bindings[0]
	for _, binding := range channel.Bindings {
		if binding.Platform.String() == obj.Platform {
			selected = binding
			break
		}
	}

	profile, err := r.deps.UsersRepository.GetByID(ctx, selected.UserID)
	if err != nil {
		if errors.Is(err, usersmodel.ErrNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("get dashboard platform profile: %w", err)
	}

	account := mappers.PlatformProfileToLinkedAccount(selected.Platform, profile)
	return &account, nil
}

// Plan is the resolver for the plan field.
func (r *dashboardResolver) Plan(ctx context.Context, obj *gqlmodel.Dashboard) (*gqlmodel.Plan, error) {
	// Use dataloader to get plan by channel ID
	return data_loader.GetPlanByChannelID(
		ctx, data_loader.GetPlayByChannelId{
			ChannelID: obj.ID,
			PlanID:    obj.PlanID,
		},
	)
}

// AuthenticatedUserSelectDashboard is the resolver for the authenticatedUserSelectDashboard field.
func (r *mutationResolver) AuthenticatedUserSelectDashboard(ctx context.Context, dashboardID string) (bool, error) {
	if err := r.deps.Sessions.SetSessionSelectedDashboard(ctx, dashboardID); err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// AuthenticatedUserUpdateSettings is the resolver for the authenticatedUserUpdateSettings field.
func (r *mutationResolver) AuthenticatedUserUpdateSettings(ctx context.Context, opts gqlmodel.UserUpdateSettingsInput) (bool, error) {
	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	entity := &model.Users{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where("id = ?", user.ID).
		First(entity).Error; err != nil {
		return false, fmt.Errorf("failed to get user: %w", err)
	}

	if opts.HideOnLandingPage.IsSet() {
		entity.HideOnLandingPage = *opts.HideOnLandingPage.Value()
	}

	if err := r.deps.Gorm.
		WithContext(ctx).
		Save(entity).Error; err != nil {
		return false, fmt.Errorf("failed to save user: %w", err)
	}

	return true, nil
}

// AuthenticatedUserRegenerateAPIKey is the resolver for the authenticatedUserRegenerateApiKey field.
func (r *mutationResolver) AuthenticatedUserRegenerateAPIKey(ctx context.Context) (string, error) {
	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return "", gqlerrors.HandleError(err)
	}

	entity := &model.Users{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where("id = ?", user.ID).
		First(entity).Error; err != nil {
		return "", fmt.Errorf("failed to get user: %w", err)
	}

	entity.ApiKey = uuid.NewString()

	if err := r.deps.Gorm.
		WithContext(ctx).
		Save(entity).Error; err != nil {
		return "", fmt.Errorf("failed to save user: %w", err)
	}

	return entity.ApiKey, nil
}

// AuthenticatedUserUpdatePublicPage is the resolver for the authenticatedUserUpdatePublicPage field.
func (r *mutationResolver) AuthenticatedUserUpdatePublicPage(ctx context.Context, opts gqlmodel.UserUpdatePublicSettingsInput) (bool, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return false, gqlerrors.HandleError(err)
	}

	if dashboardID == "" {
		return false, fmt.Errorf("selected dashboard is not set")
	}

	currentSettings := &model.ChannelPublicSettings{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where(
			"channel_id = ?",
			dashboardID,
		).
		Preload("SocialLinks").
		// init default settings
		FirstOrInit(
			currentSettings,
			&model.ChannelPublicSettings{
				ChannelID: dashboardID,
			},
		).
		Error; err != nil {
		return false, fmt.Errorf("failed to get public settings: %w", err)
	}

	txErr := r.deps.Gorm.WithContext(ctx).Transaction(
		func(tx *gorm.DB) error {
			if opts.Description.IsSet() {
				currentSettings.Description = null.StringFromPtr(opts.Description.Value())
			}

			if opts.SocialLinks.IsSet() {
				if err := tx.
					Where("settings_id = ?", currentSettings.ID).
					Delete(&model.ChannelPublicSettingsSocialLink{}).
					Error; err != nil {
					return gqlerrors.HandleError(err)
				}

				links := make([]model.ChannelPublicSettingsSocialLink, 0, len(opts.SocialLinks.Value()))
				for _, link := range opts.SocialLinks.Value() {
					links = append(
						links,
						model.ChannelPublicSettingsSocialLink{
							ID:         uuid.New(),
							SettingsID: currentSettings.ID,
							Title:      link.Title,
							Href:       link.Href,
						},
					)
				}

				currentSettings.SocialLinks = links
			}

			return tx.Save(currentSettings).Error
		},
	)

	if txErr != nil {
		return false, fmt.Errorf("failed to update public settings: %w", txErr)
	}

	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	if err := r.deps.Sessions.SessionLogout(ctx); err != nil {
		return false, gqlerrors.HandleError(err)
	}

	return true, nil
}

// UnlinkPlatformAccount is the resolver for the unlinkPlatformAccount field.
func (r *mutationResolver) UnlinkPlatformAccount(ctx context.Context, platform string) (bool, error) {
	entityPlatform := platformentity.Platform(platform)
	if !entityPlatform.IsValid() {
		return false, fmt.Errorf("unsupported platform: %s", platform)
	}
	if r.deps.CurrentPlatform == nil {
		return false, fmt.Errorf("current platform session is not configured")
	}
	currentPlatform, err := r.deps.CurrentPlatform.GetCurrentPlatform(ctx)
	if err != nil {
		return false, fmt.Errorf("get current platform: %w", err)
	}
	if currentPlatform == entityPlatform.String() {
		return false, errCannotUnlinkCurrentPlatform
	}
	dashboardID, err := r.selectedChannelPlatformDashboard(ctx)
	if err != nil {
		return false, err
	}
	if r.deps.Sessions == nil {
		return false, fmt.Errorf("sessions service is not configured")
	}
	if r.deps.DashboardAccess == nil {
		return false, fmt.Errorf("dashboard access service is not configured")
	}

	user, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return false, fmt.Errorf("get authenticated user: %w", err)
	}
	if !user.IsBotAdmin {
		isOwner, ownerErr := r.deps.DashboardAccess.IsOwner(ctx, user.ID, dashboardID)
		if ownerErr != nil {
			return false, fmt.Errorf("check dashboard ownership: %w", ownerErr)
		}
		if !isOwner {
			return false, fmt.Errorf("only the channel owner or a bot admin can manage platform identities")
		}
	}
	if r.deps.ChannelPlatformBindingsService == nil {
		return false, fmt.Errorf("channel platform binding service is not configured")
	}

	if err := r.deps.ChannelPlatformBindingsService.Disconnect(ctx, dashboardID, entityPlatform); err != nil {
		return false, err
	}

	return true, nil
}

// AuthenticatedUser is the resolver for the authenticatedUser field.
func (r *queryResolver) AuthenticatedUser(ctx context.Context) (*gqlmodel.AuthenticatedUser, error) {
	sessionUser, err := r.deps.Sessions.GetAuthenticatedUserModel(ctx)
	if err != nil {
		return nil, fmt.Errorf("not authenticated: %w", err)
	}

	dashboardId, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	user := model.Users{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where("id = ?", sessionUser.ID).
		Preload("Channel").
		First(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	authedUser := &gqlmodel.AuthenticatedUser{
		ID:                  user.ID,
		IsBotAdmin:          user.IsBotAdmin,
		IsBanned:            user.IsBanned,
		HideOnLandingPage:   user.HideOnLandingPage,
		APIKey:              user.ApiKey,
		SelectedDashboardID: dashboardId,
	}

	if user.Channel != nil {
		authedUser.PlanID = user.Channel.PlanID
	}

	if parsedDashboardID, parseErr := uuid.Parse(dashboardId); parseErr == nil {
		channel, channelErr := r.deps.ChannelService.GetChannelByID(ctx, parsedDashboardID)
		if channelErr == nil && !channel.IsNil() {
			twitchBinding, twitchConfig, found, configErr := channel.TwitchBinding()
			if configErr != nil {
				return nil, fmt.Errorf("parse Twitch channel binding configuration: %w", configErr)
			}
			if found {
				enabled := twitchBinding.Enabled
				authedUser.IsEnabled = &enabled
				isBotModerator := twitchConfig.IsBotMod
				authedUser.IsBotModerator = &isBotModerator
				if twitchConfig.BotID != "" {
					botID := twitchConfig.BotID
					authedUser.BotID = &botID
				}
			}
		}
	}

	return authedUser, nil
}

// UserPublicSettings is the resolver for the userPublicSettings field.
func (r *queryResolver) UserPublicSettings(ctx context.Context, userID *string) (*gqlmodel.PublicSettings, error) {
	dashboardId, _ := r.deps.Sessions.GetSelectedDashboard(ctx)

	var idForFetch string
	var channelID *string
	if userID != nil {
		user, err := r.deps.UsersRepository.GetByPlatformID(ctx, platformentity.PlatformTwitch, *userID)
		if err != nil && !errors.Is(err, usersmodel.ErrNotFound) {
			return nil, fmt.Errorf("get user by twitch platform id: %w", err)
		}

		if err == nil {
			channel, err := r.deps.ChannelService.GetChannelByBindingUserID(ctx, user.Platform, user.ID)
			if err != nil && !errors.Is(err, channelsrepository.ErrNotFound) {
				return nil, fmt.Errorf("get channel by twitch user id: %w", err)
			}

			if err == nil {
				resolvedChannelID := channel.ID.String()
				idForFetch = resolvedChannelID
				channelID = &resolvedChannelID
			}
		}

		if idForFetch == "" {
			return &gqlmodel.PublicSettings{
				ChannelID:   nil,
				Description: nil,
				SocialLinks: []gqlmodel.SocialLink{},
			}, nil
		}
	} else if dashboardId != "" {
		idForFetch = dashboardId
		channelID = &dashboardId
	}

	if idForFetch == "" {
		return nil, fmt.Errorf("id for fetch not setted in request or session")
	}

	entity := &model.ChannelPublicSettings{}
	if err := r.deps.Gorm.
		WithContext(ctx).
		Where(
			"channel_id = ?",
			idForFetch,
		).
		Preload("SocialLinks").
		Find(entity).Error; err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	settings := &gqlmodel.PublicSettings{
		ChannelID:   channelID,
		Description: entity.Description.Ptr(),
		SocialLinks: lo.Map(
			entity.SocialLinks,
			func(item model.ChannelPublicSettingsSocialLink, _ int) gqlmodel.SocialLink {
				return gqlmodel.SocialLink{
					Title: item.Title,
					Href:  item.Href,
				}
			},
		),
	}

	return settings, nil
}

// AuthLink is the resolver for the authLink field.
func (r *queryResolver) AuthLink(ctx context.Context, redirectTo string) (string, error) {
	if redirectTo == "" {
		return "", fmt.Errorf("incorrect auth link %s", redirectTo)
	}

	authorizeURL, err := r.deps.Auth.StartTwitchAuth(ctx, redirectTo)
	if err != nil {
		return "", gqlerrors.HandleError(err)
	}

	return authorizeURL, nil
}

// ChannelUserInfo is the resolver for the channelUserInfo field.
func (r *queryResolver) ChannelUserInfo(ctx context.Context, userID string) (*gqlmodel.ChannelUserInfo, error) {
	dashboardID, err := r.deps.Sessions.GetSelectedDashboard(ctx)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	info, err := r.deps.UsersService.GetChannelUserInfo(
		ctx, users.ChannelUserInfoInput{
			ChannelID: dashboardID,
			UserID:    userID,
		},
	)
	if err != nil {
		return nil, gqlerrors.HandleError(err)
	}

	return &gqlmodel.ChannelUserInfo{
		UserID:            info.ID,
		IsMod:             info.IsMod,
		IsVip:             info.IsVip,
		IsSubscriber:      info.IsSubscriber,
		WatchedMs:         info.Watched,
		Messages:          info.Messages,
		UsedEmotes:        info.UsedEmotes,
		UsedChannelPoints: info.UsedChannelPoints,
		FollowerSince:     info.FollowerSince,
	}, nil
}

// AuthenticatedUser returns graph.AuthenticatedUserResolver implementation.
func (r *Resolver) AuthenticatedUser() graph.AuthenticatedUserResolver {
	return &authenticatedUserResolver{r}
}

// ChannelUserInfo returns graph.ChannelUserInfoResolver implementation.
func (r *Resolver) ChannelUserInfo() graph.ChannelUserInfoResolver {
	return &channelUserInfoResolver{r}
}

// Dashboard returns graph.DashboardResolver implementation.
func (r *Resolver) Dashboard() graph.DashboardResolver { return &dashboardResolver{r} }

type authenticatedUserResolver struct{ *Resolver }
type channelUserInfoResolver struct{ *Resolver }
type dashboardResolver struct{ *Resolver }

